USE [master]
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'temp5', FILENAME = N'H:\tempDb\DATA\temp5.ndf' , SIZE = 139264KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'temp6', FILENAME = N'H:\tempDb\DATA\temp6.ndf' , SIZE = 139264KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'temp7', FILENAME = N'H:\tempDb\DATA\temp7.ndf' , SIZE = 139264KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [tempdb] ADD FILE ( NAME = N'temp8', FILENAME = N'H:\tempDb\DATA\temp8.ndf' , SIZE = 139264KB , FILEGROWTH = 65536KB )
GO
