-- Shanky
USE [master]
GO
ALTER DATABASE [Integrations] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Integrations] MODIFY FILE ( NAME = N'Integrations_log', MAXSIZE = UNLIMITED)
GO
ALTER DATABASE Logs SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE Logs MODIFY FILE ( NAME = N'Logs_log', MAXSIZE = UNLIMITED)
GO
ALTER DATABASE Queue SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE Queue MODIFY FILE ( NAME = N'Queue_log', MAXSIZE = UNLIMITED)
GO
ALTER DATABASE Temp SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE Temp MODIFY FILE ( NAME = N'Temp_log', MAXSIZE = UNLIMITED)
GO

-- into03 
USE [master]
GO
ALTER DATABASE [Ploomes_Callback] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Ploomes_Callback] MODIFY FILE ( NAME = N'Ploomes_Callback_log', MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
GO

-- PRD04 - IDP
USE [master]
GO
ALTER DATABASE [Ploomes_IdentityProvider] MODIFY FILE ( NAME = N'Ploomes_IdentityProvider', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_IdentityProvider] MODIFY FILE ( NAME = N'Ploomes_IdentityProvider_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

-- MODO ANALITCS

USE [master]
GO
ALTER DATABASE [Ploomes_Reports] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Ploomes_Reports] MODIFY FILE ( NAME = N'Ploomes_Reports', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_Reports] MODIFY FILE ( NAME = N'Ploomes_Reports_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO


-- MODO ANALITCS EU

USE [master]
GO
ALTER DATABASE [Ploomes_Reports] SET COMPATIBILITY_LEVEL = 160
GO

GO
ALTER DATABASE [Ploomes_Reports] MODIFY FILE ( NAME = N'Ploomes_Reports_Index', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_Reports] MODIFY FILE ( NAME = N'Ploomes_Reports', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_Reports] MODIFY FILE ( NAME = N'Ploomes_Reports_log', MAXSIZE = UNLIMITED, FILEGROWTH = 1048576KB )
GO

-- IDP US
USE [master]
GO
ALTER DATABASE [Ploomes_IdentityProvider] SET COMPATIBILITY_LEVEL = 160
GO

GO
ALTER DATABASE [Ploomes_IdentityProvider] MODIFY FILE ( NAME = N'Ploomes_IdentityProvider_INDEX', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_IdentityProvider] MODIFY FILE ( NAME = N'Ploomes_IdentityProvider', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_IdentityProvider] MODIFY FILE ( NAME = N'Ploomes_IdentityProvider_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

-- Shard01

USE [master]
GO
ALTER DATABASE [Ploomes_CRM] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX', FILEGROWTH = 2097152KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_02', FILEGROWTH = 2097152KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_03', FILEGROWTH = 2097152KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_04', FILEGROWTH = 2097152KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'PloomesCRM_log', FILEGROWTH = 131072KB )
GO

USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

-- shard02
USE [master]
GO
ALTER DATABASE [Ploomes_CRM] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_02', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_03', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_04', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM', FILEGROWTH = 2097152KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_logs', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO


-- shardd04
USE [master]
GO
ALTER DATABASE [Ploomes_CRM] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_02', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_03', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_04', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM', FILEGROWTH = 2097152KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

-- SHARD05 

USE [master]
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_02', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_03', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_04', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM', FILEGROWTH = 3096576KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO


USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_EMG', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_EMG_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

-- SHARD06

USE [master]
GO
ALTER DATABASE [Ploomes_CRM] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_02', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_03', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_04', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_logs', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO


-- SHARD07

USE [master]
GO
ALTER DATABASE [Ploomes_CRM] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_BKP', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_BKP_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO


USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

-- SHARD08
USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

USE [master]
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

--SHARD09

USE [master]
GO
ALTER DATABASE [Ploomes_CRM] SET COMPATIBILITY_LEVEL = 160
GO

GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM', FILEGROWTH = 2097152KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_02', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_03', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_04', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

USE [master]
GO
ALTER DATABASE [Ploomes_CRM_logs] SET COMPATIBILITY_LEVEL = 160
GO

GO
ALTER DATABASE [Ploomes_CRM_logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM_logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO


-- SHARD10
USE [master]
GO

GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_02', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_03', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_04', FILEGROWTH = 524288KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] SET COMPATIBILITY_LEVEL = 160
GO

GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO

-- Shard11 

USE [master]
GO
ALTER DATABASE [Ploomes_CRM_Logs] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM_Logs] MODIFY FILE ( NAME = N'Ploomes_CRM_Logs_log', MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
GO

USE [master]
GO
ALTER DATABASE [Ploomes_CRM] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_02', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_03', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_INDEX_04', FILEGROWTH = 131072KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM', FILEGROWTH = 1048576KB )
GO
ALTER DATABASE [Ploomes_CRM] MODIFY FILE ( NAME = N'Ploomes_CRM_log', MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
GO
