USE [master]
GO
ALTER LOGIN [fellipe.sena] WITH PASSWORD=N'Cp5dn8iZGQDNHOL0MMOx' Must_change,  
DEFAULT_DATABASE=[Ploomes_CRM], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
ALTER LOGIN [henrique.andrade] WITH PASSWORD=N'Cp5dn8iZGQDNHOL0MMOx' Must_change,  
DEFAULT_DATABASE=[Ploomes_CRM], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
ALTER LOGIN [vinicius.lojhan] WITH PASSWORD=N'Cp5dn8iZGQDNHOL0MMOx'  Must_change,  
DEFAULT_DATABASE=[Ploomes_CRM], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
ALTER LOGIN [fernando.lotti] WITH PASSWORD=N'Cp5dn8iZGQDNHOL0MMOx'   Must_change,  
DEFAULT_DATABASE=[Ploomes_CRM], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
ALTER LOGIN [leandro.bernades] WITH PASSWORD=N'Cp5dn8iZGQDNHOL0MMOx' Must_change, 
DEFAULT_DATABASE=[Ploomes_CRM], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO
ALTER LOGIN [matheus.campanini] WITH PASSWORD=N'Cp5dn8iZGQDNHOL0MMOx'Must_change, 
DEFAULT_DATABASE=[Ploomes_CRM], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO