/**
AccountId
16316
DateTime
2023-07-05T10:23:43.7895426-03:00
duration
25020
ElapsedMilliseconds
25020
EndPoint
/GeneralSearch
FinishDate
2023-07-05T10:24:08.8073703-03:00


**/
SET STATISTICS IO ON;  
SET STATISTICS XML ON
SELECT TOP (20) 
    [Project1].[ID_UsuarioView] AS [ID_UsuarioView], 
    [Project1].[C1] AS [C1], 
    [Project1].[ID_Entidade] AS [ID_Entidade], 
    [Project1].[ID_Item] AS [ID_Item], 
    [Project1].[BuscaTexto] AS [BuscaTexto], 
    [Project1].[BuscaInteiro] AS [BuscaInteiro], 
    [Project1].[ID_Cliente] AS [ID_Cliente], 
    [Project1].[ID_Oportunidade] AS [ID_Oportunidade], 
    [Project1].[ID_Venda] AS [ID_Venda], 
    [Project1].[ID_CotacaoRevisao] AS [ID_CotacaoRevisao], 
    [Project1].[ID_Lead] AS [ID_Lead], 
    [Project1].[ID_Usuario] AS [ID_Usuario], 
    [Project1].[NomeCliente] AS [NomeCliente], 
    [Project1].[Ordem] AS [Ordem], 
    [Project1].[C2] AS [C2], 
    [Project1].[C3] AS [C3], 
    [Project1].[ID_Usuario1] AS [ID_Usuario1], 
    [Project1].[ID] AS [ID], 
    [Project1].[Descricao] AS [Descricao], 
    [Project1].[C4] AS [C4], 
    [Project1].[C5] AS [C5], 
    [Project1].[C6] AS [C6], 
    [Project1].[AvatarUrl] AS [AvatarUrl], 
    [Project1].[C7] AS [C7], 
    [Project1].[Nome] AS [Nome], 
    [Project1].[C8] AS [C8], 
    [Project1].[C9] AS [C9], 
    [Project1].[C10] AS [C10], 
    [Project1].[C11] AS [C11], 
    [Project1].[NomeContato] AS [NomeContato], 
    [Project1].[C12] AS [C12], 
    [Project1].[NomeEmpresa] AS [NomeEmpresa], 
    [Project1].[C13] AS [C13], 
    [Project1].[C14] AS [C14], 
    [Project1].[C15] AS [C15], 
    [Project1].[C16] AS [C16], 
    [Project1].[Numero] AS [Numero], 
    [Project1].[C17] AS [C17], 
    [Project1].[Codigo] AS [Codigo], 
    [Project1].[C18] AS [C18], 
    [Project1].[C19] AS [C19], 
    [Project1].[C20] AS [C20], 
    [Project1].[C21] AS [C21], 
    [Project1].[ID_Tipo] AS [ID_Tipo], 
    [Project1].[C22] AS [C22], 
    [Project1].[Nome1] AS [Nome1], 
    [Project1].[C23] AS [C23], 
    [Project1].[ID_Cliente1] AS [ID_Cliente1], 
    [Project1].[C24] AS [C24], 
    [Project1].[C25] AS [C25], 
    [Project1].[C26] AS [C26], 
    [Project1].[Titulo] AS [Titulo], 
    [Project1].[C27] AS [C27], 
    [Project1].[ID_Oportunidade1] AS [ID_Oportunidade1], 
    [Project1].[C28] AS [C28], 
    [Project1].[C29] AS [C29], 
    [Project1].[C30] AS [C30], 
    [Project1].[GenderId] AS [GenderId], 
    [Project1].[C31] AS [C31], 
    [Project1].[SingularUnitName] AS [SingularUnitName], 
    [Project1].[C32] AS [C32], 
    [Project1].[IconId] AS [IconId], 
    [Project1].[C33] AS [C33], 
    [Project1].[ID_Funil] AS [ID_Funil], 
    [Project1].[C34] AS [C34], 
    [Project1].[C35] AS [C35], 
    [Project1].[C36] AS [C36], 
    [Project1].[C37] AS [C37], 
    [Project1].[C38] AS [C38], 
    [Project1].[C39] AS [C39], 
    [Project1].[Codigo1] AS [Codigo1], 
    [Project1].[C40] AS [C40], 
    [Project1].[C41] AS [C41], 
    [Project1].[C42] AS [C42], 
    [Project1].[C43] AS [C43], 
    [Project1].[ID_Tipo1] AS [ID_Tipo1], 
    [Project1].[C44] AS [C44], 
    [Project1].[Nome2] AS [Nome2], 
    [Project1].[C45] AS [C45], 
    [Project1].[ID_Cliente2] AS [ID_Cliente2], 
    [Project1].[C46] AS [C46], 
    [Project1].[C47] AS [C47], 
    [Project1].[C48] AS [C48], 
    [Project1].[Titulo1] AS [Titulo1], 
    [Project1].[C49] AS [C49], 
    [Project1].[ID_Oportunidade2] AS [ID_Oportunidade2], 
    [Project1].[C50] AS [C50], 
    [Project1].[C51] AS [C51], 
    [Project1].[C52] AS [C52], 
    [Project1].[GenderId1] AS [GenderId1], 
    [Project1].[C53] AS [C53], 
    [Project1].[SingularUnitName1] AS [SingularUnitName1], 
    [Project1].[C54] AS [C54], 
    [Project1].[IconId1] AS [IconId1], 
    [Project1].[C55] AS [C55], 
    [Project1].[ID_Funil1] AS [ID_Funil1], 
    [Project1].[C56] AS [C56], 
    [Project1].[C57] AS [C57], 
    [Project1].[C58] AS [C58], 
    [Project1].[C59] AS [C59], 
    [Project1].[C60] AS [C60], 
    [Project1].[C61] AS [C61], 
    [Project1].[Titulo2] AS [Titulo2], 
    [Project1].[C62] AS [C62], 
    [Project1].[C63] AS [C63], 
    [Project1].[C64] AS [C64], 
    [Project1].[C65] AS [C65], 
    [Project1].[GenderId2] AS [GenderId2], 
    [Project1].[C66] AS [C66], 
    [Project1].[SingularUnitName2] AS [SingularUnitName2], 
    [Project1].[C67] AS [C67], 
    [Project1].[IconId2] AS [IconId2], 
    [Project1].[C68] AS [C68], 
    [Project1].[ID_Funil2] AS [ID_Funil2], 
    [Project1].[C69] AS [C69], 
    [Project1].[C70] AS [C70], 
    [Project1].[C71] AS [C71], 
    [Project1].[ID_Tipo2] AS [ID_Tipo2], 
    [Project1].[C72] AS [C72], 
    [Project1].[Nome3] AS [Nome3], 
    [Project1].[C73] AS [C73], 
    [Project1].[ID_Cliente3] AS [ID_Cliente3], 
    [Project1].[C74] AS [C74], 
    [Project1].[C75] AS [C75], 
    [Project1].[C76] AS [C76], 
    [Project1].[C77] AS [C77], 
    [Project1].[C78] AS [C78], 
    [Project1].[CNPJFiltro] AS [CNPJFiltro], 
    [Project1].[C79] AS [C79], 
    [Project1].[CPFFiltro] AS [CPFFiltro], 
    [Project1].[C80] AS [C80], 
    [Project1].[ID_Tipo3] AS [ID_Tipo3], 
    [Project1].[C81] AS [C81], 
    [Project1].[Nome4] AS [Nome4], 
    [Project1].[C82] AS [C82], 
    [Project1].[C83] AS [C83], 
    [Project1].[C84] AS [C84], 
    [Project1].[C85] AS [C85], 
    [Project1].[CNPJFiltro1] AS [CNPJFiltro1], 
    [Project1].[C86] AS [C86], 
    [Project1].[Nome5] AS [Nome5], 
    [Project1].[C87] AS [C87], 
    [Project1].[ID_Cliente4] AS [ID_Cliente4], 
    [Project1].[C88] AS [C88], 
    [Project1].[C89] AS [C89], 
    [Project1].[C90] AS [C90], 
    [Project1].[C91] AS [C91], 
    [Project1].[C92] AS [C92], 
    [Project1].[C93] AS [C93], 
    [Project1].[C94] AS [C94], 
    [Project1].[C95] AS [C95]
    FROM ( SELECT 
        [Extent1].[ID_UsuarioView] AS [ID_UsuarioView], 
        [Extent1].[ID_Entidade] AS [ID_Entidade], 
        [Extent1].[ID_Item] AS [ID_Item], 
        [Extent1].[BuscaTexto] AS [BuscaTexto], 
        [Extent1].[BuscaInteiro] AS [BuscaInteiro], 
        [Extent1].[ID_Cliente] AS [ID_Cliente], 
        [Extent1].[ID_Oportunidade] AS [ID_Oportunidade], 
        [Extent1].[ID_Venda] AS [ID_Venda], 
        [Extent1].[ID_CotacaoRevisao] AS [ID_CotacaoRevisao], 
        [Extent1].[ID_Lead] AS [ID_Lead], 
        [Extent1].[ID_Usuario] AS [ID_Usuario], 
        [Extent1].[NomeCliente] AS [NomeCliente], 
        [Extent1].[Ordem] AS [Ordem], 
        [Extent2].[ID_Usuario] AS [ID_Usuario1], 
        [Extent2].[ID] AS [ID], 
        [Extent2].[Descricao] AS [Descricao], 
        [Extent3].[Nome] AS [Nome], 
        [Extent3].[AvatarUrl] AS [AvatarUrl], 
        [Extent4].[NomeEmpresa] AS [NomeEmpresa], 
        [Extent4].[NomeContato] AS [NomeContato], 
        [Extent5].[ID_Cliente] AS [ID_Cliente1], 
        [Extent5].[ID_Oportunidade] AS [ID_Oportunidade1], 
        [Extent5].[Codigo] AS [Codigo], 
        [Extent5].[Numero] AS [Numero], 
        [Extent6].[ID_Tipo] AS [ID_Tipo], 
        [Extent6].[Nome] AS [Nome1], 
        [Extent7].[Titulo] AS [Titulo], 
        [Extent7].[ID_Funil] AS [ID_Funil], 
        [Extent8].[SingularUnitName] AS [SingularUnitName], 
        [Extent8].[GenderId] AS [GenderId], 
        [Extent8].[IconId] AS [IconId], 
        [Extent9].[Codigo] AS [Codigo1], 
        [Extent9].[ID_Cliente] AS [ID_Cliente2], 
        [Extent9].[ID_Oportunidade] AS [ID_Oportunidade2], 
        [Extent10].[ID_Tipo] AS [ID_Tipo1], 
        [Extent10].[Nome] AS [Nome2], 
        [Extent11].[Titulo] AS [Titulo1], 
        [Extent11].[ID_Funil] AS [ID_Funil1], 
        [Extent12].[SingularUnitName] AS [SingularUnitName1], 
        [Extent12].[GenderId] AS [GenderId1], 
        [Extent12].[IconId] AS [IconId1], 
        [Extent13].[Titulo] AS [Titulo2], 
        [Extent13].[ID_Cliente] AS [ID_Cliente3], 
        [Extent13].[ID_Funil] AS [ID_Funil2], 
        [Extent14].[SingularUnitName] AS [SingularUnitName2], 
        [Extent14].[GenderId] AS [GenderId2], 
        [Extent14].[IconId] AS [IconId2], 
        [Extent15].[ID_Tipo] AS [ID_Tipo2], 
        [Extent15].[Nome] AS [Nome3], 
        [Extent16].[ID_Tipo] AS [ID_Tipo3], 
        [Extent16].[Nome] AS [Nome4], 
        [Extent16].[CNPJFiltro] AS [CNPJFiltro], 
        [Extent16].[CPFFiltro] AS [CPFFiltro], 
        [Extent16].[ID_Cliente] AS [ID_Cliente4], 
        [Extent17].[Nome] AS [Nome5], 
        [Extent17].[CNPJFiltro] AS [CNPJFiltro1], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C1], 
        N'Entity' AS [C2], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C3], 
        N'User' AS [C4], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C5], 
        N'AvatarUrl' AS [C6], 
        N'Name' AS [C7], 
        N'Id' AS [C8], 
        N'Lead' AS [C9], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C10], 
        N'PersonName' AS [C11], 
        N'CompanyName' AS [C12], 
        N'Id' AS [C13], 
        N'Quote' AS [C14], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C15], 
        N'ReviewNumber' AS [C16], 
        N'QuoteNumber' AS [C17], 
        N'Id' AS [C18], 
        N'Contact' AS [C19], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C20], 
        N'TypeId' AS [C21], 
        N'Name' AS [C22], 
        N'Id' AS [C23], 
        N'Deal' AS [C24], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C25], 
        N'Title' AS [C26], 
        N'Id' AS [C27], 
        N'Pipeline' AS [C28], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C29], 
        N'GenderId' AS [C30], 
        N'SingularUnitName' AS [C31], 
        N'IconId' AS [C32], 
        N'Id' AS [C33], 
        CASE WHEN ([Extent7].[ID_Funil] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C34], 
        CASE WHEN ([Extent5].[ID_Oportunidade] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C35], 
        CASE WHEN ([Extent5].[ID_Cliente] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C36], 
        N'Order' AS [C37], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C38], 
        N'OrderNumber' AS [C39], 
        N'Id' AS [C40], 
        N'Contact' AS [C41], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C42], 
        N'TypeId' AS [C43], 
        N'Name' AS [C44], 
        N'Id' AS [C45], 
        N'Deal' AS [C46], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C47], 
        N'Title' AS [C48], 
        N'Id' AS [C49], 
        N'Pipeline' AS [C50], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C51], 
        N'GenderId' AS [C52], 
        N'SingularUnitName' AS [C53], 
        N'IconId' AS [C54], 
        N'Id' AS [C55], 
        CASE WHEN ([Extent11].[ID_Funil] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C56], 
        CASE WHEN ([Extent9].[ID_Oportunidade] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C57], 
        CASE WHEN ([Extent9].[ID_Cliente] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C58], 
        N'Deal' AS [C59], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C60], 
        N'Title' AS [C61], 
        N'Id' AS [C62], 
        N'Pipeline' AS [C63], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C64], 
        N'GenderId' AS [C65], 
        N'SingularUnitName' AS [C66], 
        N'IconId' AS [C67], 
        N'Id' AS [C68], 
        N'Contact' AS [C69], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C70], 
        N'TypeId' AS [C71], 
        N'Name' AS [C72], 
        N'Id' AS [C73], 
        CASE WHEN ([Extent13].[ID_Cliente] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C74], 
        CASE WHEN ([Extent13].[ID_Funil] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C75], 
        N'Contact' AS [C76], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C77], 
        N'CNPJ' AS [C78], 
        N'CPF' AS [C79], 
        N'TypeId' AS [C80], 
        N'Name' AS [C81], 
        N'Id' AS [C82], 
        N'Company' AS [C83], 
        N'3043df52-7185-476a-a949-6e496f6e0dfe' AS [C84], 
        N'CNPJ' AS [C85], 
        N'Name' AS [C86], 
        N'Id' AS [C87], 
        CASE WHEN ([Extent16].[ID_Cliente] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C88], 
        CASE WHEN ([Extent1].[ID_Cliente] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C89], 
        CASE WHEN ([Extent1].[ID_Oportunidade] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C90], 
        CASE WHEN ([Extent1].[ID_Venda] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C91], 
        CASE WHEN ([Extent1].[ID_CotacaoRevisao] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C92], 
        CASE WHEN ([Extent1].[ID_Lead] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C93], 
        CASE WHEN ([Extent1].[ID_Usuario] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C94], 
        cast(0 as bit) AS [C95]
        FROM                 [dbo].[Vw_PesquisaGeral] AS [Extent1]
        INNER JOIN [dbo].[SVw_PesquisaGeral_Entidade] AS [Extent2] ON ([Extent1].[ID_Entidade] = [Extent2].[ID]) AND ([Extent1].[ID_UsuarioView] = [Extent2].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Usuario] AS [Extent3] ON ([Extent1].[ID_Usuario] = [Extent3].[ID]) AND ([Extent1].[ID_UsuarioView] = [Extent3].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Lead] AS [Extent4] ON ([Extent1].[ID_Lead] = [Extent4].[ID]) AND ([Extent1].[ID_UsuarioView] = [Extent4].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Cotacao_Revisao] AS [Extent5] ON ([Extent1].[ID_CotacaoRevisao] = [Extent5].[ID]) AND ([Extent1].[ID_UsuarioView] = [Extent5].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Cliente] AS [Extent6] ON ([Extent5].[ID_Cliente] = [Extent6].[ID]) AND ([Extent5].[ID_Usuario] = [Extent6].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Oportunidade] AS [Extent7] ON ([Extent5].[ID_Oportunidade] = [Extent7].[ID]) AND ([Extent5].[ID_Usuario] = [Extent7].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Oportunidade_Funil] AS [Extent8] ON ([Extent7].[ID_Funil] = [Extent8].[ID]) AND ([Extent7].[ID_Usuario] = [Extent8].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Venda] AS [Extent9] ON ([Extent1].[ID_Venda] = [Extent9].[ID]) AND ([Extent1].[ID_UsuarioView] = [Extent9].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Cliente] AS [Extent10] ON ([Extent9].[ID_Cliente] = [Extent10].[ID]) AND ([Extent9].[ID_Usuario] = [Extent10].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Oportunidade] AS [Extent11] ON ([Extent9].[ID_Oportunidade] = [Extent11].[ID]) AND ([Extent9].[ID_Usuario] = [Extent11].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Oportunidade_Funil] AS [Extent12] ON ([Extent11].[ID_Funil] = [Extent12].[ID]) AND ([Extent11].[ID_Usuario] = [Extent12].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Oportunidade] AS [Extent13] ON ([Extent1].[ID_Oportunidade] = [Extent13].[ID]) AND ([Extent1].[ID_UsuarioView] = [Extent13].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Oportunidade_Funil] AS [Extent14] ON ([Extent13].[ID_Funil] = [Extent14].[ID]) AND ([Extent13].[ID_Usuario] = [Extent14].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Cliente] AS [Extent15] ON ([Extent13].[ID_Cliente] = [Extent15].[ID]) AND ([Extent13].[ID_Usuario] = [Extent15].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Cliente] AS [Extent16] ON ([Extent1].[ID_Cliente] = [Extent16].[ID]) AND ([Extent1].[ID_UsuarioView] = [Extent16].[ID_Usuario])
        LEFT OUTER JOIN [dbo].[SVw_Cliente] AS [Extent17] ON ([Extent16].[ID_Cliente] = [Extent17].[ID]) AND ([Extent16].[ID_Usuario] = [Extent17].[ID_Usuario])
        WHERE ([Extent1].[ID_UsuarioView] = 109694) AND ([Extent1].[BuscaTexto] LIKE '%Aurenir%' ESCAPE N'~')
    )  AS [Project1]
    ORDER BY [Project1].[Ordem] ASC, [Project1].[ID_Entidade] ASC, [Project1].[ID_Item] ASC

SET STATISTICS IO OFF;


--sp_helpindex 'cliente'
--ID_ClientePloomes, ID_Responsavel, ID_Importacao
CREATE INDEX IX_Cliente_ID_ClientePloomes2 ON cliente (ID_ClientePloomes, ID_Responsavel, ID_Importacao) on INDEX_04
GO
drop index if exists cliente.IX_Cliente_ID_ClientePloomes2


SELECT
	sc.name AS SchemaName,
	ob.name AS Table_name,
	id.name AS Index_name,
	us.user_seeks,
	us.user_scans,
	us.user_updates,
	(us.user_seeks + us.user_scans + us.user_lookups) [totalAcesso],
	us.last_user_scan,
	us.last_user_seek,
	us.last_user_lookup
FROM sys.dm_db_index_usage_stats us
JOIN sys.objects  ob ON us.OBJECT_ID = ob.OBJECT_ID
JOIN sys.indexes  id ON id.index_id = us.index_id AND us.OBJECT_ID = id.OBJECT_ID
JOIN sys.schemas  sc ON sc.schema_id = ob.schema_id
WHERE ob.name in ('Cliente')
--Where id.name not like 'PK%'
ORDER BY 5 DESC