DECLARE @p__linq__0 int = 10024347,
@p__linq__1 int = 50000246,
@p__linq__2 int = 500001178,
@p__linq__3 int = 50000245,
@p__linq__4 int = 500001174,
@p__linq__7 int = 50000247,
@p__linq__5 int = 0,
@p__linq__6 int = 15


SELECT 
    [Project4].[ID] AS [ID], 
    [Project4].[ID_Usuario] AS [ID_Usuario], 
    [Project4].[C1] AS [C1], 
    [Project4].[C3] AS [C3], 
    [Project4].[CNPJFiltro] AS [CNPJFiltro], 
    [Project4].[C4] AS [C4], 
    [Project4].[ID_Tipo] AS [ID_Tipo], 
    [Project4].[C5] AS [C5], 
    [Project4].[Data_PrimeiraTarefa] AS [Data_PrimeiraTarefa], 
    [Project4].[C6] AS [C6], 
    [Project4].[Edita] AS [Edita], 
    [Project4].[C7] AS [C7], 
    [Project4].[Nome] AS [Nome], 
    [Project4].[C8] AS [C8], 
    [Project4].[C9] AS [C9], 
    [Project4].[C14] AS [C10], 
    [Project4].[ID_UsuarioView] AS [ID_UsuarioView], 
    [Project4].[C10] AS [C11], 
    [Project4].[ID1] AS [ID1], 
    [Project4].[ID_Campo] AS [ID_Campo], 
    [Project4].[Chave_Campo] AS [Chave_Campo], 
    [Project4].[ID_Cliente] AS [ID_Cliente], 
    [Project4].[ValorTexto] AS [ValorTexto], 
    [Project4].[ValorTextoMultilinha] AS [ValorTextoMultilinha], 
    [Project4].[ValorInteiro] AS [ValorInteiro], 
    [Project4].[ValorDecimal] AS [ValorDecimal], 
    [Project4].[ValorDataHora] AS [ValorDataHora], 
    [Project4].[ValorBooleano] AS [ValorBooleano], 
    [Project4].[ID_OpcaoValor] AS [ID_OpcaoValor], 
    [Project4].[ObjectValueName] AS [ObjectValueName], 
    [Project4].[ID_UsuarioValor] AS [ID_UsuarioValor], 
    [Project4].[UserValueName] AS [UserValueName], 
    [Project4].[UserValueAvatarUrl] AS [UserValueAvatarUrl], 
    [Project4].[ID_ProdutoValor] AS [ID_ProdutoValor], 
    [Project4].[ProductValueName] AS [ProductValueName], 
    [Project4].[AttachmentValueId] AS [AttachmentValueId], 
    [Project4].[AttachmentValueName] AS [AttachmentValueName], 
    [Project4].[ContactValueId] AS [ContactValueId], 
    [Project4].[ContactValueName] AS [ContactValueName], 
    [Project4].[ContactValueTypeId] AS [ContactValueTypeId], 
    [Project4].[ContactValueRegister] AS [ContactValueRegister], 
    [Project4].[CurrencyValueId] AS [CurrencyValueId], 
    [Project4].[AttachmentItemValueId] AS [AttachmentItemValueId], 
    [Project4].[AttachmentItemValueName] AS [AttachmentItemValueName], 
    [Project4].[C11] AS [C12], 
    [Project4].[C12] AS [C13], 
    [Project4].[ID_Usuario1] AS [ID_Usuario1], 
    [Project4].[ID2] AS [ID2], 
    [Project4].[Descricao] AS [Descricao], 
    [Project4].[Sigla] AS [Sigla], 
    [Project4].[Edita1] AS [Edita1], 
    [Project4].[LastUpdateDate] AS [LastUpdateDate], 
    [Project4].[C13] AS [C14]
    FROM ( SELECT 
        [Limit1].[ID_Usuario] AS [ID_Usuario], 
        [Limit1].[ID] AS [ID], 
        [Limit1].[ID_Tipo] AS [ID_Tipo], 
        [Limit1].[Nome] AS [Nome], 
        [Limit1].[CNPJFiltro] AS [CNPJFiltro], 
        [Limit1].[Data_PrimeiraTarefa] AS [Data_PrimeiraTarefa], 
        [Limit1].[OrdemTarefas] AS [OrdemTarefas], 
        [Limit1].[Edita] AS [Edita], 
        [Limit1].[C1] AS [C1], 
        [Limit1].[C3] AS [C3], 
        [Limit1].[C4] AS [C4], 
        [Limit1].[C5] AS [C5], 
        [Limit1].[C6] AS [C6], 
        [Limit1].[C7] AS [C7], 
        [Limit1].[C8] AS [C8], 
        [Limit1].[C9] AS [C9], 
        [Join1].[ID_UsuarioView] AS [ID_UsuarioView], 
        [Join1].[ID1] AS [ID1], 
        [Join1].[ID_Campo] AS [ID_Campo], 
        [Join1].[Chave_Campo] AS [Chave_Campo], 
        [Join1].[ID_Cliente] AS [ID_Cliente], 
        [Join1].[ValorTexto] AS [ValorTexto], 
        [Join1].[ValorTextoMultilinha] AS [ValorTextoMultilinha], 
        [Join1].[ValorInteiro] AS [ValorInteiro], 
        [Join1].[ValorDecimal] AS [ValorDecimal], 
        [Join1].[ValorDataHora] AS [ValorDataHora], 
        [Join1].[ValorBooleano] AS [ValorBooleano], 
        [Join1].[ID_OpcaoValor] AS [ID_OpcaoValor], 
        [Join1].[ObjectValueName] AS [ObjectValueName], 
        [Join1].[ID_UsuarioValor] AS [ID_UsuarioValor], 
        [Join1].[UserValueName] AS [UserValueName], 
        [Join1].[UserValueAvatarUrl] AS [UserValueAvatarUrl], 
        [Join1].[ID_ProdutoValor] AS [ID_ProdutoValor], 
        [Join1].[ProductValueName] AS [ProductValueName], 
        [Join1].[AttachmentValueId] AS [AttachmentValueId], 
        [Join1].[AttachmentValueName] AS [AttachmentValueName], 
        [Join1].[ContactValueId] AS [ContactValueId], 
        [Join1].[ContactValueName] AS [ContactValueName], 
        [Join1].[ContactValueTypeId] AS [ContactValueTypeId], 
        [Join1].[ContactValueRegister] AS [ContactValueRegister], 
        [Join1].[CurrencyValueId] AS [CurrencyValueId], 
        [Join1].[AttachmentItemValueId] AS [AttachmentItemValueId], 
        [Join1].[AttachmentItemValueName] AS [AttachmentItemValueName], 
        [Join1].[ID_Usuario] AS [ID_Usuario1], 
        [Join1].[ID2] AS [ID2], 
        [Join1].[Descricao] AS [Descricao], 
        [Join1].[Sigla] AS [Sigla], 
        [Join1].[Edita] AS [Edita1], 
        [Join1].[LastUpdateDate] AS [LastUpdateDate], 
        CASE WHEN ([Join1].[ID_UsuarioView] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'826f733e-bb23-487e-886b-9363f833a016' END AS [C10], 
        CASE WHEN ([Join1].[ID_UsuarioView] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'CurrencyValue' END AS [C11], 
        CASE WHEN ([Join1].[ID_UsuarioView] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'826f733e-bb23-487e-886b-9363f833a016' END AS [C12], 
        CASE WHEN ([Join1].[ID_UsuarioView] IS NULL) THEN CAST(NULL AS bit) WHEN (([Join1].[ID_Usuario] IS NULL) AND ([Join1].[ID2] IS NULL)) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C13], 
        CASE WHEN ([Join1].[ID_UsuarioView] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C14]
        FROM   (SELECT [Project3].[ID_Usuario] AS [ID_Usuario], [Project3].[ID] AS [ID], [Project3].[ID_Tipo] AS [ID_Tipo], [Project3].[Nome] AS [Nome], [Project3].[CNPJFiltro] AS [CNPJFiltro], [Project3].[Data_PrimeiraTarefa] AS [Data_PrimeiraTarefa], [Project3].[OrdemTarefas] AS [OrdemTarefas], [Project3].[Edita] AS [Edita], [Project3].[C1] AS [C1], [Project3].[C3] AS [C3], [Project3].[C4] AS [C4], [Project3].[C5] AS [C5], [Project3].[C6] AS [C6], [Project3].[C7] AS [C7], [Project3].[C8] AS [C8], [Project3].[C9] AS [C9]
            FROM ( SELECT 
                @p__linq__7 AS [p__linq__7], 
                [Extent1].[ID_Usuario] AS [ID_Usuario], 
                [Extent1].[ID] AS [ID], 
                [Extent1].[ID_Tipo] AS [ID_Tipo], 
                [Extent1].[Nome] AS [Nome], 
                [Extent1].[CNPJFiltro] AS [CNPJFiltro], 
                [Extent1].[Data_PrimeiraTarefa] AS [Data_PrimeiraTarefa], 
                [Extent1].[OrdemTarefas] AS [OrdemTarefas], 
                [Extent1].[Edita] AS [Edita], 
                N'826f733e-bb23-487e-886b-9363f833a016' AS [C1], 
                N'CNPJ' AS [C3], 
                N'TypeId' AS [C4], 
                N'FirstTaskDate' AS [C5], 
                N'Editable' AS [C6], 
                N'Name' AS [C7], 
                N'Id' AS [C8], 
                N'OtherProperties' AS [C9]
                FROM [dbo].[SVw_Cliente] AS [Extent1]
                WHERE ([Extent1].[ID_Usuario] = @p__linq__0) AND ( EXISTS (SELECT 
                    1 AS [C1]
                    FROM [dbo].[SVw_Campo_Valor_Cliente] AS [Extent2]
                    WHERE ([Extent1].[ID_Usuario] = [Extent2].[ID_UsuarioView]) AND ([Extent1].[ID] = [Extent2].[ID_Cliente]) AND ([Extent2].[ID_Campo] = @p__linq__1) AND ([Extent2].[ValorInteiro] = @p__linq__2)
                )) AND ( EXISTS (SELECT 
                    1 AS [C1]
                    FROM [dbo].[SVw_Campo_Valor_Cliente] AS [Extent3]
                    WHERE ([Extent1].[ID_Usuario] = [Extent3].[ID_UsuarioView]) AND ([Extent1].[ID] = [Extent3].[ID_Cliente]) AND ([Extent3].[ID_Campo] = @p__linq__3) AND ([Extent3].[ValorInteiro] = @p__linq__4)
                ))
            )  AS [Project3]
            ORDER BY [Project3].[OrdemTarefas] ASC, [Project3].[Data_PrimeiraTarefa] ASC, [Project3].[ID] ASC
            OFFSET @p__linq__5 ROWS FETCH NEXT @p__linq__6 ROWS ONLY  ) AS [Limit1]
        LEFT OUTER JOIN  (SELECT [Extent4].[ID_UsuarioView] AS [ID_UsuarioView], [Extent4].[ID] AS [ID1], [Extent4].[ID_Campo] AS [ID_Campo], [Extent4].[Chave_Campo] AS [Chave_Campo], [Extent4].[ID_Cliente] AS [ID_Cliente], [Extent4].[ValorTexto] AS [ValorTexto], [Extent4].[ValorTextoMultilinha] AS [ValorTextoMultilinha], [Extent4].[ValorInteiro] AS [ValorInteiro], [Extent4].[ValorDecimal] AS [ValorDecimal], [Extent4].[ValorDataHora] AS [ValorDataHora], [Extent4].[ValorBooleano] AS [ValorBooleano], [Extent4].[ID_OpcaoValor] AS [ID_OpcaoValor], [Extent4].[ObjectValueName] AS [ObjectValueName], [Extent4].[ID_UsuarioValor] AS [ID_UsuarioValor], [Extent4].[UserValueName] AS [UserValueName], [Extent4].[UserValueAvatarUrl] AS [UserValueAvatarUrl], [Extent4].[ID_ProdutoValor] AS [ID_ProdutoValor], [Extent4].[ProductValueName] AS [ProductValueName], [Extent4].[AttachmentValueId] AS [AttachmentValueId], [Extent4].[AttachmentValueName] AS [AttachmentValueName], [Extent4].[ContactValueId] AS [ContactValueId], [Extent4].[ContactValueName] AS [ContactValueName], [Extent4].[ContactValueTypeId] AS [ContactValueTypeId], [Extent4].[ContactValueRegister] AS [ContactValueRegister], [Extent4].[CurrencyValueId] AS [CurrencyValueId], [Extent4].[AttachmentItemValueId] AS [AttachmentItemValueId], [Extent4].[AttachmentItemValueName] AS [AttachmentItemValueName], [Extent5].[ID_Usuario] AS [ID_Usuario], [Extent5].[ID] AS [ID2], [Extent5].[Descricao] AS [Descricao], [Extent5].[Sigla] AS [Sigla], [Extent5].[Edita] AS [Edita], [Extent5].[LastUpdateDate] AS [LastUpdateDate]
            FROM  [dbo].[SVw_Campo_Valor_Cliente] AS [Extent4]
            LEFT OUTER JOIN [dbo].[SVw_Moeda] AS [Extent5] ON ([Extent4].[ID_UsuarioView] = [Extent5].[ID_Usuario]) AND ([Extent4].[CurrencyValueId] = [Extent5].[ID]) ) AS [Join1] ON ([Limit1].[ID_Usuario] = [Join1].[ID_UsuarioView]) AND ([Limit1].[ID] = [Join1].[ID_Cliente]) AND ([Join1].[ID_Campo] = @p__linq__7)
    )  AS [Project4]
    ORDER BY [Project4].[OrdemTarefas] ASC, [Project4].[Data_PrimeiraTarefa] ASC, [Project4].[ID] ASC, [Project4].[ID_Usuario] ASC, [Project4].[C14] ASC