--(10031617 int,0 bit,500349367 int,75 int,50003041 int,10241922 int)

SELECT 
    [UnionAll2].[ID_Recorrencia] AS [C1], 
    [UnionAll2].[ID_Usuario] AS [C2], 
    [UnionAll2].[ID_Usuario1] AS [C3], 
    [UnionAll2].[ID] AS [C4], 
    [UnionAll2].[ID_Usuario2] AS [C5], 
    [UnionAll2].[ID1] AS [C6], 
    [UnionAll2].[ID2] AS [C7], 
    [UnionAll2].[ID_Usuario3] AS [C8], 
    [UnionAll2].[ID_Usuario4] AS [C9], 
    [UnionAll2].[ID3] AS [C10], 
    [UnionAll2].[ID_Usuario5] AS [C11], 
    [UnionAll2].[C2] AS [C12], 
    [UnionAll2].[ID_Usuario6] AS [C13], 
    [UnionAll2].[C3] AS [C14], 
    [UnionAll2].[Descricao] AS [C15], 
    [UnionAll2].[ID_Usuario7] AS [C16], 
    [UnionAll2].[C4] AS [C17], 
    [UnionAll2].[DataRecorrencia] AS [C18], 
    [UnionAll2].[ID_Usuario8] AS [C19], 
    [UnionAll2].[C5] AS [C20], 
    [UnionAll2].[DataCriacao] AS [C21], 
    [UnionAll2].[ID_Usuario9] AS [C22], 
    [UnionAll2].[C6] AS [C23], 
    [UnionAll2].[Concluido] AS [C24], 
    [UnionAll2].[ID_Usuario10] AS [C25], 
    [UnionAll2].[C7] AS [C26], 
    [UnionAll2].[Longitude] AS [C27], 
    [UnionAll2].[ID_Usuario11] AS [C28], 
    [UnionAll2].[C8] AS [C29], 
    [UnionAll2].[Latitude] AS [C30], 
    [UnionAll2].[ID_Usuario12] AS [C31], 
    [UnionAll2].[C9] AS [C32], 
    [UnionAll2].[Titulo] AS [C33], 
    [UnionAll2].[ID_Usuario13] AS [C34], 
    [UnionAll2].[C10] AS [C35], 
    [UnionAll2].[ID_Recorrencia1] AS [C36], 
    [UnionAll2].[ID_Usuario14] AS [C37], 
    [UnionAll2].[C11] AS [C38], 
    [UnionAll2].[ID_Usuario15] AS [C39], 
    [UnionAll2].[C12] AS [C40], 
    [UnionAll2].[ID_Usuario16] AS [C41], 
    [UnionAll2].[C13] AS [C42], 
    [UnionAll2].[Descricao1] AS [C43], 
    [UnionAll2].[ID_Usuario17] AS [C44], 
    [UnionAll2].[C14] AS [C45], 
    [UnionAll2].[ID_Classe] AS [C46], 
    [UnionAll2].[ID_Usuario18] AS [C47], 
    [UnionAll2].[C15] AS [C48], 
    [UnionAll2].[ID_Usuario19] AS [C49], 
    [UnionAll2].[C16] AS [C50], 
    [UnionAll2].[ID_Usuario20] AS [C51], 
    [UnionAll2].[C17] AS [C52], 
    [UnionAll2].[ID_Usuario21] AS [C53], 
    [UnionAll2].[C18] AS [C54], 
    [UnionAll2].[ID_Responsavel] AS [C55], 
    [UnionAll2].[ID_Usuario22] AS [C56], 
    [UnionAll2].[C19] AS [C57], 
    [UnionAll2].[Nome] AS [C58], 
    [UnionAll2].[ID_Usuario23] AS [C59], 
    [UnionAll2].[C20] AS [C60], 
    [UnionAll2].[ID_Cliente] AS [C61], 
    [UnionAll2].[ID_Usuario24] AS [C62], 
    [UnionAll2].[C21] AS [C63], 
    [UnionAll2].[ID_Usuario25] AS [C64], 
    [UnionAll2].[C22] AS [C65], 
    [UnionAll2].[ID_Usuario26] AS [C66], 
    [UnionAll2].[C23] AS [C67], 
    [UnionAll2].[ID_Responsavel1] AS [C68], 
    [UnionAll2].[ID_Usuario27] AS [C69], 
    [UnionAll2].[C24] AS [C70], 
    [UnionAll2].[C25] AS [C71], 
    [UnionAll2].[ID_Usuario28] AS [C72], 
    [UnionAll2].[C26] AS [C73], 
    [UnionAll2].[ID_Usuario29] AS [C74], 
    [UnionAll2].[C27] AS [C75], 
    [UnionAll2].[ID_Usuario30] AS [C76], 
    [UnionAll2].[C28] AS [C77], 
    [UnionAll2].[Titulo1] AS [C78], 
    [UnionAll2].[ID_Usuario31] AS [C79], 
    [UnionAll2].[C29] AS [C80], 
    [UnionAll2].[ID_Oportunidade] AS [C81], 
    [UnionAll2].[ID_Usuario32] AS [C82], 
    [UnionAll2].[C30] AS [C83], 
    [UnionAll2].[ID_Usuario33] AS [C84], 
    [UnionAll2].[C31] AS [C85], 
    [UnionAll2].[ID_Usuario34] AS [C86], 
    [UnionAll2].[C32] AS [C87], 
    [UnionAll2].[AvatarUrl] AS [C88], 
    [UnionAll2].[ID_Usuario35] AS [C89], 
    [UnionAll2].[C33] AS [C90], 
    [UnionAll2].[Nome1] AS [C91], 
    [UnionAll2].[ID_Usuario36] AS [C92], 
    [UnionAll2].[C34] AS [C93], 
    [UnionAll2].[ID_Responsavel2] AS [C94], 
    [UnionAll2].[ID_Usuario37] AS [C95], 
    [UnionAll2].[C35] AS [C96], 
    [UnionAll2].[C36] AS [C97], 
    [UnionAll2].[C37] AS [C98], 
    [UnionAll2].[C38] AS [C99], 
    [UnionAll2].[C39] AS [C100], 
    [UnionAll2].[C1] AS [C101], 
    [UnionAll2].[ID4] AS [C102], 
    [UnionAll2].[C40] AS [C103], 
    [UnionAll2].[ID5] AS [C104], 
    [UnionAll2].[C41] AS [C105], 
    [UnionAll2].[ID6] AS [C106], 
    [UnionAll2].[ID7] AS [C107], 
    [UnionAll2].[C42] AS [C108], 
    [UnionAll2].[ID8] AS [C109], 
    [UnionAll2].[C43] AS [C110], 
    [UnionAll2].[ID9] AS [C111], 
    [UnionAll2].[C44] AS [C112], 
    [UnionAll2].[AvatarUrl1] AS [C113], 
    [UnionAll2].[ID10] AS [C114], 
    [UnionAll2].[C45] AS [C115], 
    [UnionAll2].[Nome2] AS [C116], 
    [UnionAll2].[ID11] AS [C117], 
    [UnionAll2].[C46] AS [C118], 
    [UnionAll2].[ID_Usuario38] AS [C119], 
    [UnionAll2].[C47] AS [C120], 
    [UnionAll2].[C48] AS [C121], 
    [UnionAll2].[C49] AS [C122], 
    [UnionAll2].[C50] AS [C123], 
    [UnionAll2].[C51] AS [C124], 
    [UnionAll2].[C52] AS [C125], 
    [UnionAll2].[C53] AS [C126], 
    [UnionAll2].[C54] AS [C127], 
    [UnionAll2].[C55] AS [C128], 
    [UnionAll2].[C56] AS [C129], 
    [UnionAll2].[C57] AS [C130], 
    [UnionAll2].[C58] AS [C131], 
    [UnionAll2].[C59] AS [C132], 
    [UnionAll2].[C60] AS [C133], 
    [UnionAll2].[C61] AS [C134], 
    [UnionAll2].[C62] AS [C135], 
    [UnionAll2].[C63] AS [C136], 
    [UnionAll2].[C64] AS [C137], 
    [UnionAll2].[C65] AS [C138], 
    [UnionAll2].[C66] AS [C139], 
    [UnionAll2].[C67] AS [C140], 
    [UnionAll2].[C68] AS [C141], 
    [UnionAll2].[C69] AS [C142], 
    [UnionAll2].[C70] AS [C143], 
    [UnionAll2].[C71] AS [C144], 
    [UnionAll2].[C72] AS [C145], 
    [UnionAll2].[C73] AS [C146], 
    [UnionAll2].[C74] AS [C147], 
    [UnionAll2].[C75] AS [C148], 
    [UnionAll2].[C76] AS [C149], 
    [UnionAll2].[C77] AS [C150], 
    [UnionAll2].[C78] AS [C151], 
    [UnionAll2].[C79] AS [C152], 
    [UnionAll2].[C80] AS [C153], 
    [UnionAll2].[C81] AS [C154], 
    [UnionAll2].[C82] AS [C155], 
    [UnionAll2].[C83] AS [C156], 
    [UnionAll2].[C84] AS [C157], 
    [UnionAll2].[C85] AS [C158], 
    [UnionAll2].[C86] AS [C159], 
    [UnionAll2].[C87] AS [C160], 
    [UnionAll2].[C88] AS [C161], 
    [UnionAll2].[C89] AS [C162], 
    [UnionAll2].[C90] AS [C163], 
    [UnionAll2].[C91] AS [C164], 
    [UnionAll2].[C92] AS [C165], 
    [UnionAll2].[C93] AS [C166], 
    [UnionAll2].[C94] AS [C167], 
    [UnionAll2].[C95] AS [C168], 
    [UnionAll2].[C96] AS [C169], 
    [UnionAll2].[C97] AS [C170], 
    [UnionAll2].[C98] AS [C171], 
    [UnionAll2].[C99] AS [C172], 
    [UnionAll2].[C100] AS [C173], 
    [UnionAll2].[C101] AS [C174], 
    [UnionAll2].[C102] AS [C175], 
    [UnionAll2].[C103] AS [C176], 
    [UnionAll2].[C104] AS [C177], 
    [UnionAll2].[C105] AS [C178]
    FROM  (SELECT 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS int) ELSE 1 END AS [C1], 
        [Limit1].[ID_Recorrencia] AS [ID_Recorrencia], 
        [Limit1].[ID_Usuario] AS [ID_Usuario], 
        [Limit1].[ID_Usuario1] AS [ID_Usuario1], 
        [Limit1].[ID] AS [ID], 
        [Limit1].[ID_Usuario2] AS [ID_Usuario2], 
        [Limit1].[ID1] AS [ID1], 
        [Limit1].[ID2] AS [ID2], 
        [Limit1].[ID_Usuario3] AS [ID_Usuario3], 
        [Limit1].[ID_Usuario4] AS [ID_Usuario4], 
        [Limit1].[ID3] AS [ID3], 
        [Limit1].[ID_Usuario] AS [ID_Usuario5], 
        [Limit1].[C1] AS [C2], 
        [Limit1].[ID_Usuario] AS [ID_Usuario6], 
        [Limit1].[C2] AS [C3], 
        [Limit1].[Descricao] AS [Descricao], 
        [Limit1].[ID_Usuario] AS [ID_Usuario7], 
        [Limit1].[C3] AS [C4], 
        [Limit1].[DataRecorrencia] AS [DataRecorrencia], 
        [Limit1].[ID_Usuario] AS [ID_Usuario8], 
        [Limit1].[C4] AS [C5], 
        [Limit1].[DataCriacao] AS [DataCriacao], 
        [Limit1].[ID_Usuario] AS [ID_Usuario9], 
        [Limit1].[C5] AS [C6], 
        [Limit1].[Concluido] AS [Concluido], 
        [Limit1].[ID_Usuario] AS [ID_Usuario10], 
        [Limit1].[C6] AS [C7], 
        [Limit1].[Longitude] AS [Longitude], 
        [Limit1].[ID_Usuario] AS [ID_Usuario11], 
        [Limit1].[C7] AS [C8], 
        [Limit1].[Latitude] AS [Latitude], 
        [Limit1].[ID_Usuario] AS [ID_Usuario12], 
        [Limit1].[C8] AS [C9], 
        [Limit1].[Titulo] AS [Titulo], 
        [Limit1].[ID_Usuario] AS [ID_Usuario13], 
        [Limit1].[C9] AS [C10], 
        [Limit1].[ID_Recorrencia] AS [ID_Recorrencia1], 
        [Limit1].[ID_Usuario] AS [ID_Usuario14], 
        [Limit1].[C10] AS [C11], 
        [Limit1].[ID_Usuario] AS [ID_Usuario15], 
        [Limit1].[C11] AS [C12], 
        [Limit1].[ID_Usuario] AS [ID_Usuario16], 
        [Limit1].[C12] AS [C13], 
        [Limit1].[Descricao1] AS [Descricao1], 
        [Limit1].[ID_Usuario] AS [ID_Usuario17], 
        [Limit1].[C13] AS [C14], 
        [Limit1].[ID_Classe] AS [ID_Classe], 
        [Limit1].[ID_Usuario] AS [ID_Usuario18], 
        [Limit1].[C14] AS [C15], 
        [Limit1].[ID_Usuario] AS [ID_Usuario19], 
        [Limit1].[C15] AS [C16], 
        [Limit1].[ID_Usuario] AS [ID_Usuario20], 
        [Limit1].[C16] AS [C17], 
        [Limit1].[ID_Usuario] AS [ID_Usuario21], 
        [Limit1].[C17] AS [C18], 
        [Limit1].[ID_Responsavel] AS [ID_Responsavel], 
        [Limit1].[ID_Usuario] AS [ID_Usuario22], 
        [Limit1].[C18] AS [C19], 
        [Limit1].[Nome] AS [Nome], 
        [Limit1].[ID_Usuario] AS [ID_Usuario23], 
        [Limit1].[C19] AS [C20], 
        [Limit1].[ID_Cliente] AS [ID_Cliente], 
        [Limit1].[ID_Usuario] AS [ID_Usuario24], 
        [Limit1].[C20] AS [C21], 
        [Limit1].[ID_Usuario] AS [ID_Usuario25], 
        [Limit1].[C21] AS [C22], 
        [Limit1].[ID_Usuario] AS [ID_Usuario26], 
        [Limit1].[C22] AS [C23], 
        [Limit1].[ID_Responsavel] AS [ID_Responsavel1], 
        [Limit1].[ID_Usuario] AS [ID_Usuario27], 
        [Limit1].[C23] AS [C24], 
        [Limit1].[C24] AS [C25], 
        [Limit1].[ID_Usuario] AS [ID_Usuario28], 
        [Limit1].[C25] AS [C26], 
        [Limit1].[ID_Usuario] AS [ID_Usuario29], 
        [Limit1].[C26] AS [C27], 
        [Limit1].[ID_Usuario] AS [ID_Usuario30], 
        [Limit1].[C27] AS [C28], 
        [Limit1].[Titulo1] AS [Titulo1], 
        [Limit1].[ID_Usuario] AS [ID_Usuario31], 
        [Limit1].[C28] AS [C29], 
        [Limit1].[ID_Oportunidade] AS [ID_Oportunidade], 
        [Limit1].[ID_Usuario] AS [ID_Usuario32], 
        [Limit1].[C29] AS [C30], 
        [Limit1].[ID_Usuario] AS [ID_Usuario33], 
        [Limit1].[C30] AS [C31], 
        [Limit1].[ID_Usuario] AS [ID_Usuario34], 
        [Limit1].[C31] AS [C32], 
        [Limit1].[AvatarUrl] AS [AvatarUrl], 
        [Limit1].[ID_Usuario] AS [ID_Usuario35], 
        [Limit1].[C32] AS [C33], 
        [Limit1].[Nome1] AS [Nome1], 
        [Limit1].[ID_Usuario] AS [ID_Usuario36], 
        [Limit1].[C33] AS [C34], 
        [Limit1].[ID_Responsavel1] AS [ID_Responsavel2], 
        [Limit1].[ID_Usuario] AS [ID_Usuario37], 
        [Limit1].[C34] AS [C35], 
        [Limit1].[C35] AS [C36], 
        [Limit1].[C36] AS [C37], 
        [Limit1].[C37] AS [C38], 
        [Limit1].[C38] AS [C39], 
        [Join5].[ID4] AS [ID4], 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' END AS [C40], 
        [Join5].[ID4] AS [ID5], 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'Id' END AS [C41], 
        [Join5].[ID4] AS [ID6], 
        [Join5].[ID4] AS [ID7], 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'User' END AS [C42], 
        [Join5].[ID4] AS [ID8], 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' END AS [C43], 
        [Join5].[ID4] AS [ID9], 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'AvatarUrl' END AS [C44], 
        [Join5].[AvatarUrl] AS [AvatarUrl1], 
        [Join5].[ID4] AS [ID10], 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'Name' END AS [C45], 
        [Join5].[Nome] AS [Nome2], 
        [Join5].[ID4] AS [ID11], 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS varchar(1)) ELSE N'Id' END AS [C46], 
        [Join5].[ID_Usuario5] AS [ID_Usuario38], 
        CASE WHEN ([Join5].[ID4] IS NULL) THEN CAST(NULL AS bit) ELSE cast(0 as bit) END AS [C47], 
        CAST(NULL AS int) AS [C48], 
        CAST(NULL AS varchar(1)) AS [C49], 
        CAST(NULL AS int) AS [C50], 
        CAST(NULL AS int) AS [C51], 
        CAST(NULL AS int) AS [C52], 
        CAST(NULL AS varchar(1)) AS [C53], 
        CAST(NULL AS int) AS [C54], 
        CAST(NULL AS varchar(1)) AS [C55], 
        CAST(NULL AS varchar(1)) AS [C56], 
        CAST(NULL AS int) AS [C57], 
        CAST(NULL AS float) AS [C58], 
        CAST(NULL AS datetime2) AS [C59], 
        CAST(NULL AS bit) AS [C60], 
        CAST(NULL AS int) AS [C61], 
        CAST(NULL AS varchar(1)) AS [C62], 
        CAST(NULL AS int) AS [C63], 
        CAST(NULL AS varchar(1)) AS [C64], 
        CAST(NULL AS varchar(1)) AS [C65], 
        CAST(NULL AS int) AS [C66], 
        CAST(NULL AS varchar(1)) AS [C67], 
        CAST(NULL AS int) AS [C68], 
        CAST(NULL AS varchar(1)) AS [C69], 
        CAST(NULL AS int) AS [C70], 
        CAST(NULL AS varchar(1)) AS [C71], 
        CAST(NULL AS int) AS [C72], 
        CAST(NULL AS varchar(1)) AS [C73], 
        CAST(NULL AS int) AS [C74], 
        CAST(NULL AS int) AS [C75], 
        CAST(NULL AS varchar(1)) AS [C76], 
        CAST(NULL AS int) AS [C77], 
        CAST(NULL AS varchar(1)) AS [C78], 
        CAST(NULL AS int) AS [C79], 
        CAST(NULL AS int) AS [C80], 
        CAST(NULL AS int) AS [C81], 
        CAST(NULL AS varchar(1)) AS [C82], 
        CAST(NULL AS int) AS [C83], 
        CAST(NULL AS varchar(1)) AS [C84], 
        CAST(NULL AS varchar(1)) AS [C85], 
        CAST(NULL AS int) AS [C86], 
        CAST(NULL AS float) AS [C87], 
        CAST(NULL AS datetime2) AS [C88], 
        CAST(NULL AS bit) AS [C89], 
        CAST(NULL AS int) AS [C90], 
        CAST(NULL AS varchar(1)) AS [C91], 
        CAST(NULL AS int) AS [C92], 
        CAST(NULL AS varchar(1)) AS [C93], 
        CAST(NULL AS varchar(1)) AS [C94], 
        CAST(NULL AS int) AS [C95], 
        CAST(NULL AS varchar(1)) AS [C96], 
        CAST(NULL AS int) AS [C97], 
        CAST(NULL AS varchar(1)) AS [C98], 
        CAST(NULL AS int) AS [C99], 
        CAST(NULL AS varchar(1)) AS [C100], 
        CAST(NULL AS int) AS [C101], 
        CAST(NULL AS varchar(1)) AS [C102], 
        CAST(NULL AS int) AS [C103], 
        CAST(NULL AS int) AS [C104], 
        CAST(NULL AS varchar(1)) AS [C105]
        FROM   (SELECT TOP (75) [Project1].[ID_Usuario] AS [ID_Usuario], [Project1].[ID_Recorrencia] AS [ID_Recorrencia], [Project1].[Titulo] AS [Titulo], [Project1].[Descricao] AS [Descricao], [Project1].[ID_Classe] AS [ID_Classe], [Project1].[ID_Cliente] AS [ID_Cliente], [Project1].[ID_Oportunidade] AS [ID_Oportunidade], [Project1].[DataRecorrencia] AS [DataRecorrencia], [Project1].[Concluido] AS [Concluido], [Project1].[Latitude] AS [Latitude], [Project1].[Longitude] AS [Longitude], [Project1].[DataCriacao] AS [DataCriacao], [Project1].[ID_Usuario1] AS [ID_Usuario1], [Project1].[ID] AS [ID], [Project1].[Descricao1] AS [Descricao1], [Project1].[ID_Usuario2] AS [ID_Usuario2], [Project1].[ID1] AS [ID1], [Project1].[Nome] AS [Nome], [Project1].[ID_Responsavel] AS [ID_Responsavel], [Project1].[ID_Usuario3] AS [ID_Usuario3], [Project1].[ID2] AS [ID2], [Project1].[Titulo1] AS [Titulo1], [Project1].[ID_Responsavel1] AS [ID_Responsavel1], [Project1].[ID_Usuario4] AS [ID_Usuario4], [Project1].[ID3] AS [ID3], [Project1].[Nome1] AS [Nome1], [Project1].[AvatarUrl] AS [AvatarUrl], [Project1].[C1] AS [C1], [Project1].[C2] AS [C2], [Project1].[C3] AS [C3], [Project1].[C4] AS [C4], [Project1].[C5] AS [C5], [Project1].[C6] AS [C6], [Project1].[C7] AS [C7], [Project1].[C8] AS [C8], [Project1].[C9] AS [C9], [Project1].[C10] AS [C10], [Project1].[C11] AS [C11], [Project1].[C12] AS [C12], [Project1].[C13] AS [C13], [Project1].[C14] AS [C14], [Project1].[C15] AS [C15], [Project1].[C16] AS [C16], [Project1].[C17] AS [C17], [Project1].[C18] AS [C18], [Project1].[C19] AS [C19], [Project1].[C20] AS [C20], [Project1].[C21] AS [C21], [Project1].[C22] AS [C22], [Project1].[C23] AS [C23], [Project1].[C24] AS [C24], [Project1].[C25] AS [C25], [Project1].[C26] AS [C26], [Project1].[C27] AS [C27], [Project1].[C28] AS [C28], [Project1].[C29] AS [C29], [Project1].[C30] AS [C30], [Project1].[C31] AS [C31], [Project1].[C32] AS [C32], [Project1].[C33] AS [C33], [Project1].[C34] AS [C34], [Project1].[C35] AS [C35], [Project1].[C36] AS [C36], [Project1].[C37] AS [C37], [Project1].[C38] AS [C38]
            FROM ( SELECT 
                [Filter1].[ID_Usuario6] AS [ID_Usuario], 
                [Filter1].[ID_Recorrencia] AS [ID_Recorrencia], 
                [Filter1].[Titulo2] AS [Titulo], 
                [Filter1].[Descricao2] AS [Descricao], 
                [Filter1].[ID_Classe1] AS [ID_Classe], 
                [Filter1].[ID_Cliente1] AS [ID_Cliente], 
                [Filter1].[ID_Oportunidade] AS [ID_Oportunidade], 
                [Filter1].[DataRecorrencia] AS [DataRecorrencia], 
                [Filter1].[Concluido] AS [Concluido], 
                [Filter1].[Latitude] AS [Latitude], 
                [Filter1].[Longitude] AS [Longitude], 
                [Filter1].[DataCriacao1] AS [DataCriacao], 
                [Filter1].[ID_Usuario7] AS [ID_Usuario1], 
                [Filter1].[ID5] AS [ID], 
                [Filter1].[Descricao3] AS [Descricao1], 
                [Filter1].[ID_Usuario8] AS [ID_Usuario2], 
                [Filter1].[ID6] AS [ID1], 
                [Filter1].[Nome] AS [Nome], 
                [Filter1].[ID_Responsavel2] AS [ID_Responsavel], 
                [Filter1].[ID_Usuario9] AS [ID_Usuario3], 
                [Filter1].[ID7] AS [ID2], 
                [Filter1].[Titulo3] AS [Titulo1], 
                [Filter1].[ID_Responsavel3] AS [ID_Responsavel1], 
                [Extent5].[ID_Usuario] AS [ID_Usuario4], 
                [Extent5].[ID] AS [ID3], 
                [Extent5].[Nome] AS [Nome1], 
                [Extent5].[AvatarUrl] AS [AvatarUrl], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C1], 
                N'Description' AS [C2], 
                N'DateTime' AS [C3], 
                N'CreateDate' AS [C4], 
                N'Finished' AS [C5], 
                N'Longitude' AS [C6], 
                N'Latitude' AS [C7], 
                N'Title' AS [C8], 
                N'Id' AS [C9], 
                N'Type' AS [C10], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C11], 
                N'Name' AS [C12], 
                N'Id' AS [C13], 
                N'Users' AS [C14], 
                N'Contact' AS [C15], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C16], 
                N'OwnerId' AS [C17], 
                N'Name' AS [C18], 
                N'Id' AS [C19], 
                N'Owner' AS [C20], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C21], 
                N'Id' AS [C22], 
                N'OtherProperties' AS [C23], 
                CASE WHEN ([Filter1].[ID_Responsavel2] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C24], 
                N'Deal' AS [C25], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C26], 
                N'Title' AS [C27], 
                N'Id' AS [C28], 
                N'Owner' AS [C29], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C30], 
                N'AvatarUrl' AS [C31], 
                N'Name' AS [C32], 
                N'Id' AS [C33], 
                N'OtherProperties' AS [C34], 
                CASE WHEN ([Filter1].[ID_Responsavel3] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C35], 
                CASE WHEN ([Filter1].[ID_Oportunidade] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C36], 
                CASE WHEN ([Filter1].[ID_Cliente1] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C37], 
                CASE WHEN ([Filter1].[ID_Classe1] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C38]
                FROM   (SELECT [Extent1].[ID_Usuario] AS [ID_Usuario6], [Extent1].[ID_Recorrencia] AS [ID_Recorrencia], [Extent1].[Titulo] AS [Titulo2], [Extent1].[Descricao] AS [Descricao2], [Extent1].[ID_Classe] AS [ID_Classe1], [Extent1].[ID_Cliente] AS [ID_Cliente1], [Extent1].[ID_Oportunidade] AS [ID_Oportunidade], [Extent1].[DataRecorrencia] AS [DataRecorrencia], [Extent1].[Concluido] AS [Concluido], [Extent1].[Latitude] AS [Latitude], [Extent1].[Longitude] AS [Longitude], [Extent1].[DataCriacao] AS [DataCriacao1], [Extent2].[ID_Usuario] AS [ID_Usuario7], [Extent2].[ID] AS [ID5], [Extent2].[Descricao] AS [Descricao3], [Extent3].[ID_Usuario] AS [ID_Usuario8], [Extent3].[ID] AS [ID6], [Extent3].[Nome] AS [Nome], [Extent3].[ID_Responsavel] AS [ID_Responsavel2], [Extent4].[ID_Usuario] AS [ID_Usuario9], [Extent4].[ID] AS [ID7], [Extent4].[Titulo] AS [Titulo3], [Extent4].[ID_Responsavel] AS [ID_Responsavel3]
                    FROM    [dbo].[SVw_Tarefa] AS [Extent1]
                    LEFT OUTER JOIN [dbo].[SVw_Tarefa_Classe] AS [Extent2] ON ([Extent1].[ID_Usuario] = [Extent2].[ID_Usuario]) AND ([Extent1].[ID_Classe] = [Extent2].[ID])
                    LEFT OUTER JOIN [dbo].[SVw_Cliente] AS [Extent3] ON ([Extent1].[ID_Usuario] = [Extent3].[ID_Usuario]) AND ([Extent1].[ID_Cliente] = [Extent3].[ID])
                    LEFT OUTER JOIN [dbo].[SVw_Oportunidade] AS [Extent4] ON ([Extent1].[ID_Usuario] = [Extent4].[ID_Usuario]) AND ([Extent1].[ID_Oportunidade] = [Extent4].[ID])
                    WHERE [Extent1].[ID_Recorrencia] > 0 ) AS [Filter1]
                LEFT OUTER JOIN [dbo].[SVw_Usuario] AS [Extent5] ON ([Filter1].[ID_Usuario9] = [Extent5].[ID_Usuario]) AND ([Filter1].[ID_Responsavel3] = [Extent5].[ID])
                WHERE ([Filter1].[ID_Usuario6] = 10031617) AND ([Filter1].[Concluido] = 0) AND ([Filter1].[ID_Recorrencia] > 500349367)
            )  AS [Project1]
            ORDER BY [Project1].[ID_Recorrencia] ASC ) AS [Limit1]
        LEFT OUTER JOIN  (SELECT [Extent6].[ID] AS [ID4], [Extent6].[ID_UsuarioView] AS [ID_UsuarioView], [Extent6].[ID_Tarefa] AS [ID_Tarefa], [Extent6].[ID_Usuario] AS [ID_Usuario5], [Extent7].[Nome] AS [Nome], [Extent7].[AvatarUrl] AS [AvatarUrl]
            FROM  [dbo].[SVw_Tarefa_Usuario] AS [Extent6]
            INNER JOIN [dbo].[SVw_Usuario] AS [Extent7] ON ([Extent6].[ID_Usuario] = [Extent7].[ID]) AND ([Extent6].[ID_UsuarioView] = [Extent7].[ID_Usuario]) ) AS [Join5] ON ([Limit1].[ID_Recorrencia] = [Join5].[ID_Tarefa]) AND ([Limit1].[ID_Usuario] = [Join5].[ID_UsuarioView])
    UNION ALL
        SELECT 
        2 AS [C1], 
        [Limit2].[ID_Recorrencia] AS [ID_Recorrencia], 
        [Limit2].[ID_Usuario] AS [ID_Usuario], 
        [Limit2].[ID_Usuario1] AS [ID_Usuario1], 
        [Limit2].[ID] AS [ID], 
        [Limit2].[ID_Usuario2] AS [ID_Usuario2], 
        [Limit2].[ID1] AS [ID1], 
        [Limit2].[ID2] AS [ID2], 
        [Limit2].[ID_Usuario3] AS [ID_Usuario3], 
        [Limit2].[ID_Usuario4] AS [ID_Usuario4], 
        [Limit2].[ID3] AS [ID3], 
        [Limit2].[ID_Usuario] AS [ID_Usuario5], 
        [Limit2].[C1] AS [C2], 
        [Limit2].[ID_Usuario] AS [ID_Usuario6], 
        [Limit2].[C2] AS [C3], 
        [Limit2].[Descricao] AS [Descricao], 
        [Limit2].[ID_Usuario] AS [ID_Usuario7], 
        [Limit2].[C3] AS [C4], 
        [Limit2].[DataRecorrencia] AS [DataRecorrencia], 
        [Limit2].[ID_Usuario] AS [ID_Usuario8], 
        [Limit2].[C4] AS [C5], 
        [Limit2].[DataCriacao] AS [DataCriacao], 
        [Limit2].[ID_Usuario] AS [ID_Usuario9], 
        [Limit2].[C5] AS [C6], 
        [Limit2].[Concluido] AS [Concluido], 
        [Limit2].[ID_Usuario] AS [ID_Usuario10], 
        [Limit2].[C6] AS [C7], 
        [Limit2].[Longitude] AS [Longitude], 
        [Limit2].[ID_Usuario] AS [ID_Usuario11], 
        [Limit2].[C7] AS [C8], 
        [Limit2].[Latitude] AS [Latitude], 
        [Limit2].[ID_Usuario] AS [ID_Usuario12], 
        [Limit2].[C8] AS [C9], 
        [Limit2].[Titulo] AS [Titulo], 
        [Limit2].[ID_Usuario] AS [ID_Usuario13], 
        [Limit2].[C9] AS [C10], 
        [Limit2].[ID_Recorrencia] AS [ID_Recorrencia1], 
        [Limit2].[ID_Usuario] AS [ID_Usuario14], 
        [Limit2].[C10] AS [C11], 
        [Limit2].[ID_Usuario] AS [ID_Usuario15], 
        [Limit2].[C11] AS [C12], 
        [Limit2].[ID_Usuario] AS [ID_Usuario16], 
        [Limit2].[C12] AS [C13], 
        [Limit2].[Descricao1] AS [Descricao1], 
        [Limit2].[ID_Usuario] AS [ID_Usuario17], 
        [Limit2].[C13] AS [C14], 
        [Limit2].[ID_Classe] AS [ID_Classe], 
        [Limit2].[ID_Usuario] AS [ID_Usuario18], 
        [Limit2].[C14] AS [C15], 
        [Limit2].[ID_Usuario] AS [ID_Usuario19], 
        [Limit2].[C15] AS [C16], 
        [Limit2].[ID_Usuario] AS [ID_Usuario20], 
        [Limit2].[C16] AS [C17], 
        [Limit2].[ID_Usuario] AS [ID_Usuario21], 
        [Limit2].[C17] AS [C18], 
        [Limit2].[ID_Responsavel] AS [ID_Responsavel], 
        [Limit2].[ID_Usuario] AS [ID_Usuario22], 
        [Limit2].[C18] AS [C19], 
        [Limit2].[Nome] AS [Nome], 
        [Limit2].[ID_Usuario] AS [ID_Usuario23], 
        [Limit2].[C19] AS [C20], 
        [Limit2].[ID_Cliente] AS [ID_Cliente], 
        [Limit2].[ID_Usuario] AS [ID_Usuario24], 
        [Limit2].[C20] AS [C21], 
        [Limit2].[ID_Usuario] AS [ID_Usuario25], 
        [Limit2].[C21] AS [C22], 
        [Limit2].[ID_Usuario] AS [ID_Usuario26], 
        [Limit2].[C22] AS [C23], 
        [Limit2].[ID_Responsavel] AS [ID_Responsavel1], 
        [Limit2].[ID_Usuario] AS [ID_Usuario27], 
        [Limit2].[C23] AS [C24], 
        [Limit2].[C24] AS [C25], 
        [Limit2].[ID_Usuario] AS [ID_Usuario28], 
        [Limit2].[C25] AS [C26], 
        [Limit2].[ID_Usuario] AS [ID_Usuario29], 
        [Limit2].[C26] AS [C27], 
        [Limit2].[ID_Usuario] AS [ID_Usuario30], 
        [Limit2].[C27] AS [C28], 
        [Limit2].[Titulo1] AS [Titulo1], 
        [Limit2].[ID_Usuario] AS [ID_Usuario31], 
        [Limit2].[C28] AS [C29], 
        [Limit2].[ID_Oportunidade] AS [ID_Oportunidade], 
        [Limit2].[ID_Usuario] AS [ID_Usuario32], 
        [Limit2].[C29] AS [C30], 
        [Limit2].[ID_Usuario] AS [ID_Usuario33], 
        [Limit2].[C30] AS [C31], 
        [Limit2].[ID_Usuario] AS [ID_Usuario34], 
        [Limit2].[C31] AS [C32], 
        [Limit2].[AvatarUrl] AS [AvatarUrl], 
        [Limit2].[ID_Usuario] AS [ID_Usuario35], 
        [Limit2].[C32] AS [C33], 
        [Limit2].[Nome1] AS [Nome1], 
        [Limit2].[ID_Usuario] AS [ID_Usuario36], 
        [Limit2].[C33] AS [C34], 
        [Limit2].[ID_Responsavel1] AS [ID_Responsavel2], 
        [Limit2].[ID_Usuario] AS [ID_Usuario37], 
        [Limit2].[C34] AS [C35], 
        [Limit2].[C35] AS [C36], 
        [Limit2].[C36] AS [C37], 
        [Limit2].[C37] AS [C38], 
        [Limit2].[C38] AS [C39], 
        CAST(NULL AS int) AS [C40], 
        CAST(NULL AS varchar(1)) AS [C41], 
        CAST(NULL AS int) AS [C42], 
        CAST(NULL AS varchar(1)) AS [C43], 
        CAST(NULL AS int) AS [C44], 
        CAST(NULL AS int) AS [C45], 
        CAST(NULL AS varchar(1)) AS [C46], 
        CAST(NULL AS int) AS [C47], 
        CAST(NULL AS varchar(1)) AS [C48], 
        CAST(NULL AS int) AS [C49], 
        CAST(NULL AS varchar(1)) AS [C50], 
        CAST(NULL AS varchar(1)) AS [C51], 
        CAST(NULL AS int) AS [C52], 
        CAST(NULL AS varchar(1)) AS [C53], 
        CAST(NULL AS varchar(1)) AS [C54], 
        CAST(NULL AS int) AS [C55], 
        CAST(NULL AS varchar(1)) AS [C56], 
        CAST(NULL AS int) AS [C57], 
        CAST(NULL AS bit) AS [C58], 
        [Join12].[ID_UsuarioView] AS [ID_UsuarioView], 
        N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C59], 
        [Join12].[ID_UsuarioView] AS [ID_UsuarioView1], 
        [Join12].[ID8] AS [ID4], 
        [Join12].[ID_Campo] AS [ID_Campo], 
        [Join12].[Chave_Campo] AS [Chave_Campo], 
        [Join12].[ID_Usuario10] AS [ID_Usuario38], 
        [Join12].[ValorTexto] AS [ValorTexto], 
        [Join12].[ValorTextoMultilinha] AS [ValorTextoMultilinha], 
        [Join12].[ValorInteiro] AS [ValorInteiro], 
        [Join12].[ValorDecimal] AS [ValorDecimal], 
        [Join12].[ValorDataHora] AS [ValorDataHora], 
        [Join12].[ValorBooleano] AS [ValorBooleano], 
        [Join12].[ID_OpcaoValor] AS [ID_OpcaoValor], 
        [Join12].[ObjectValueName] AS [ObjectValueName], 
        [Join12].[ID_UsuarioValor] AS [ID_UsuarioValor], 
        [Join12].[UserValueName] AS [UserValueName], 
        [Join12].[UserValueAvatarUrl] AS [UserValueAvatarUrl], 
        [Join12].[ID_ProdutoValor] AS [ID_ProdutoValor], 
        [Join12].[ProductValueName] AS [ProductValueName], 
        [Join12].[AttachmentValueId] AS [AttachmentValueId], 
        [Join12].[AttachmentValueName] AS [AttachmentValueName], 
        [Join12].[ContactValueId] AS [ContactValueId], 
        [Join12].[ContactValueName] AS [ContactValueName], 
        [Join12].[ContactValueTypeId] AS [ContactValueTypeId], 
        [Join12].[ContactValueRegister] AS [ContactValueRegister], 
        [Join12].[CurrencyValueId] AS [CurrencyValueId], 
        [Join12].[AttachmentItemValueId] AS [AttachmentItemValueId], 
        [Join12].[AttachmentItemValueName] AS [AttachmentItemValueName], 
        CAST(NULL AS int) AS [C60], 
        CAST(NULL AS varchar(1)) AS [C61], 
        CAST(NULL AS int) AS [C62], 
        CAST(NULL AS int) AS [C63], 
        CAST(NULL AS int) AS [C64], 
        CAST(NULL AS varchar(1)) AS [C65], 
        CAST(NULL AS int) AS [C66], 
        CAST(NULL AS varchar(1)) AS [C67], 
        CAST(NULL AS varchar(1)) AS [C68], 
        CAST(NULL AS int) AS [C69], 
        CAST(NULL AS float) AS [C70], 
        CAST(NULL AS datetime2) AS [C71], 
        CAST(NULL AS bit) AS [C72], 
        CAST(NULL AS int) AS [C73], 
        CAST(NULL AS varchar(1)) AS [C74], 
        CAST(NULL AS int) AS [C75], 
        CAST(NULL AS varchar(1)) AS [C76], 
        CAST(NULL AS varchar(1)) AS [C77], 
        CAST(NULL AS int) AS [C78], 
        CAST(NULL AS varchar(1)) AS [C79], 
        CAST(NULL AS int) AS [C80], 
        CAST(NULL AS varchar(1)) AS [C81], 
        CAST(NULL AS int) AS [C82], 
        CAST(NULL AS varchar(1)) AS [C83], 
        CAST(NULL AS int) AS [C84], 
        CAST(NULL AS varchar(1)) AS [C85], 
        CAST(NULL AS int) AS [C86], 
        CAST(NULL AS int) AS [C87], 
        CAST(NULL AS varchar(1)) AS [C88]
        FROM   (SELECT TOP (75) [Project3].[ID_Usuario] AS [ID_Usuario], [Project3].[ID_Recorrencia] AS [ID_Recorrencia], [Project3].[Titulo] AS [Titulo], [Project3].[Descricao] AS [Descricao], [Project3].[ID_Classe] AS [ID_Classe], [Project3].[ID_Cliente] AS [ID_Cliente], [Project3].[ID_Oportunidade] AS [ID_Oportunidade], [Project3].[DataRecorrencia] AS [DataRecorrencia], [Project3].[Concluido] AS [Concluido], [Project3].[Latitude] AS [Latitude], [Project3].[Longitude] AS [Longitude], [Project3].[DataCriacao] AS [DataCriacao], [Project3].[ID_Usuario1] AS [ID_Usuario1], [Project3].[ID] AS [ID], [Project3].[Descricao1] AS [Descricao1], [Project3].[ID_Usuario2] AS [ID_Usuario2], [Project3].[ID1] AS [ID1], [Project3].[Nome] AS [Nome], [Project3].[ID_Responsavel] AS [ID_Responsavel], [Project3].[ID_Usuario3] AS [ID_Usuario3], [Project3].[ID2] AS [ID2], [Project3].[Titulo1] AS [Titulo1], [Project3].[ID_Responsavel1] AS [ID_Responsavel1], [Project3].[ID_Usuario4] AS [ID_Usuario4], [Project3].[ID3] AS [ID3], [Project3].[Nome1] AS [Nome1], [Project3].[AvatarUrl] AS [AvatarUrl], [Project3].[C1] AS [C1], [Project3].[C2] AS [C2], [Project3].[C3] AS [C3], [Project3].[C4] AS [C4], [Project3].[C5] AS [C5], [Project3].[C6] AS [C6], [Project3].[C7] AS [C7], [Project3].[C8] AS [C8], [Project3].[C9] AS [C9], [Project3].[C10] AS [C10], [Project3].[C11] AS [C11], [Project3].[C12] AS [C12], [Project3].[C13] AS [C13], [Project3].[C14] AS [C14], [Project3].[C15] AS [C15], [Project3].[C16] AS [C16], [Project3].[C17] AS [C17], [Project3].[C18] AS [C18], [Project3].[C19] AS [C19], [Project3].[C20] AS [C20], [Project3].[C21] AS [C21], [Project3].[C22] AS [C22], [Project3].[C23] AS [C23], [Project3].[C24] AS [C24], [Project3].[C25] AS [C25], [Project3].[C26] AS [C26], [Project3].[C27] AS [C27], [Project3].[C28] AS [C28], [Project3].[C29] AS [C29], [Project3].[C30] AS [C30], [Project3].[C31] AS [C31], [Project3].[C32] AS [C32], [Project3].[C33] AS [C33], [Project3].[C34] AS [C34], [Project3].[C35] AS [C35], [Project3].[C36] AS [C36], [Project3].[C37] AS [C37], [Project3].[C38] AS [C38]
            FROM ( SELECT 
                50003041 AS [p__linq__4], 
                [Filter3].[ID_Usuario11] AS [ID_Usuario], 
                [Filter3].[ID_Recorrencia] AS [ID_Recorrencia], 
                [Filter3].[Titulo4] AS [Titulo], 
                [Filter3].[Descricao4] AS [Descricao], 
                [Filter3].[ID_Classe2] AS [ID_Classe], 
                [Filter3].[ID_Cliente2] AS [ID_Cliente], 
                [Filter3].[ID_Oportunidade] AS [ID_Oportunidade], 
                [Filter3].[DataRecorrencia] AS [DataRecorrencia], 
                [Filter3].[Concluido] AS [Concluido], 
                [Filter3].[Latitude] AS [Latitude], 
                [Filter3].[Longitude] AS [Longitude], 
                [Filter3].[DataCriacao2] AS [DataCriacao], 
                [Filter3].[ID_Usuario12] AS [ID_Usuario1], 
                [Filter3].[ID9] AS [ID], 
                [Filter3].[Descricao5] AS [Descricao1], 
                [Filter3].[ID_Usuario13] AS [ID_Usuario2], 
                [Filter3].[ID10] AS [ID1], 
                [Filter3].[Nome] AS [Nome], 
                [Filter3].[ID_Responsavel4] AS [ID_Responsavel], 
                [Filter3].[ID_Usuario14] AS [ID_Usuario3], 
                [Filter3].[ID11] AS [ID2], 
                [Filter3].[Titulo5] AS [Titulo1], 
                [Filter3].[ID_Responsavel5] AS [ID_Responsavel1], 
                [Extent12].[ID_Usuario] AS [ID_Usuario4], 
                [Extent12].[ID] AS [ID3], 
                [Extent12].[Nome] AS [Nome1], 
                [Extent12].[AvatarUrl] AS [AvatarUrl], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C1], 
                N'Description' AS [C2], 
                N'DateTime' AS [C3], 
                N'CreateDate' AS [C4], 
                N'Finished' AS [C5], 
                N'Longitude' AS [C6], 
                N'Latitude' AS [C7], 
                N'Title' AS [C8], 
                N'Id' AS [C9], 
                N'Type' AS [C10], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C11], 
                N'Name' AS [C12], 
                N'Id' AS [C13], 
                N'Users' AS [C14], 
                N'Contact' AS [C15], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C16], 
                N'OwnerId' AS [C17], 
                N'Name' AS [C18], 
                N'Id' AS [C19], 
                N'Owner' AS [C20], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C21], 
                N'Id' AS [C22], 
                N'OtherProperties' AS [C23], 
                CASE WHEN ([Filter3].[ID_Responsavel4] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C24], 
                N'Deal' AS [C25], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C26], 
                N'Title' AS [C27], 
                N'Id' AS [C28], 
                N'Owner' AS [C29], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C30], 
                N'AvatarUrl' AS [C31], 
                N'Name' AS [C32], 
                N'Id' AS [C33], 
                N'OtherProperties' AS [C34], 
                CASE WHEN ([Filter3].[ID_Responsavel5] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C35], 
                CASE WHEN ([Filter3].[ID_Oportunidade] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C36], 
                CASE WHEN ([Filter3].[ID_Cliente2] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C37], 
                CASE WHEN ([Filter3].[ID_Classe2] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C38]
                FROM   (SELECT [Extent8].[ID_Usuario] AS [ID_Usuario11], [Extent8].[ID_Recorrencia] AS [ID_Recorrencia], [Extent8].[Titulo] AS [Titulo4], [Extent8].[Descricao] AS [Descricao4], [Extent8].[ID_Classe] AS [ID_Classe2], [Extent8].[ID_Cliente] AS [ID_Cliente2], [Extent8].[ID_Oportunidade] AS [ID_Oportunidade], [Extent8].[DataRecorrencia] AS [DataRecorrencia], [Extent8].[Concluido] AS [Concluido], [Extent8].[Latitude] AS [Latitude], [Extent8].[Longitude] AS [Longitude], [Extent8].[DataCriacao] AS [DataCriacao2], [Extent9].[ID_Usuario] AS [ID_Usuario12], [Extent9].[ID] AS [ID9], [Extent9].[Descricao] AS [Descricao5], [Extent10].[ID_Usuario] AS [ID_Usuario13], [Extent10].[ID] AS [ID10], [Extent10].[Nome] AS [Nome], [Extent10].[ID_Responsavel] AS [ID_Responsavel4], [Extent11].[ID_Usuario] AS [ID_Usuario14], [Extent11].[ID] AS [ID11], [Extent11].[Titulo] AS [Titulo5], [Extent11].[ID_Responsavel] AS [ID_Responsavel5]
                    FROM    [dbo].[SVw_Tarefa] AS [Extent8]
                    LEFT OUTER JOIN [dbo].[SVw_Tarefa_Classe] AS [Extent9] ON ([Extent8].[ID_Usuario] = [Extent9].[ID_Usuario]) AND ([Extent8].[ID_Classe] = [Extent9].[ID])
                    LEFT OUTER JOIN [dbo].[SVw_Cliente] AS [Extent10] ON ([Extent8].[ID_Usuario] = [Extent10].[ID_Usuario]) AND ([Extent8].[ID_Cliente] = [Extent10].[ID])
                    LEFT OUTER JOIN [dbo].[SVw_Oportunidade] AS [Extent11] ON ([Extent8].[ID_Usuario] = [Extent11].[ID_Usuario]) AND ([Extent8].[ID_Oportunidade] = [Extent11].[ID])
                    WHERE [Extent8].[ID_Recorrencia] > 0 ) AS [Filter3]
                LEFT OUTER JOIN [dbo].[SVw_Usuario] AS [Extent12] ON ([Filter3].[ID_Usuario14] = [Extent12].[ID_Usuario]) AND ([Filter3].[ID_Responsavel5] = [Extent12].[ID])
                WHERE ([Filter3].[ID_Usuario11] = 10031617) AND ([Filter3].[Concluido] = 0) AND ([Filter3].[ID_Recorrencia] > 500349367)
            )  AS [Project3]
            ORDER BY [Project3].[ID_Recorrencia] ASC ) AS [Limit2]
        INNER JOIN  (SELECT [Extent13].[ID_Usuario] AS [ID_Usuario15], [Extent13].[ID] AS [ID12], [Extent15].[ID_UsuarioView] AS [ID_UsuarioView], [Extent15].[ID] AS [ID8], [Extent15].[ID_Campo] AS [ID_Campo], [Extent15].[Chave_Campo] AS [Chave_Campo], [Extent15].[ID_Usuario] AS [ID_Usuario10], [Extent15].[ValorTexto] AS [ValorTexto], [Extent15].[ValorTextoMultilinha] AS [ValorTextoMultilinha], [Extent15].[ValorInteiro] AS [ValorInteiro], [Extent15].[ValorDecimal] AS [ValorDecimal], [Extent15].[ValorDataHora] AS [ValorDataHora], [Extent15].[ValorBooleano] AS [ValorBooleano], [Extent15].[ID_OpcaoValor] AS [ID_OpcaoValor], [Extent15].[ObjectValueName] AS [ObjectValueName], [Extent15].[ID_UsuarioValor] AS [ID_UsuarioValor], [Extent15].[UserValueName] AS [UserValueName], [Extent15].[UserValueAvatarUrl] AS [UserValueAvatarUrl], [Extent15].[ID_ProdutoValor] AS [ID_ProdutoValor], [Extent15].[ProductValueName] AS [ProductValueName], [Extent15].[AttachmentValueId] AS [AttachmentValueId], [Extent15].[AttachmentValueName] AS [AttachmentValueName], [Extent15].[ContactValueId] AS [ContactValueId], [Extent15].[ContactValueName] AS [ContactValueName], [Extent15].[ContactValueTypeId] AS [ContactValueTypeId], [Extent15].[ContactValueRegister] AS [ContactValueRegister], [Extent15].[CurrencyValueId] AS [CurrencyValueId], [Extent15].[AttachmentItemValueId] AS [AttachmentItemValueId], [Extent15].[AttachmentItemValueName] AS [AttachmentItemValueName]
            FROM   [dbo].[SVw_Cliente] AS [Extent13]
            LEFT OUTER JOIN [dbo].[SVw_Usuario] AS [Extent14] ON ([Extent13].[ID_Usuario] = [Extent14].[ID_Usuario]) AND ([Extent13].[ID_Responsavel] = [Extent14].[ID])
            INNER JOIN [dbo].[SVw_Campo_Valor_Usuario] AS [Extent15] ON ([Extent14].[ID_Usuario] = [Extent15].[ID_UsuarioView]) AND ([Extent14].[ID] = [Extent15].[ID_Usuario]) ) AS [Join12] ON ([Limit2].[ID_Usuario] = [Join12].[ID_Usuario15]) AND ([Limit2].[ID_Cliente] = [Join12].[ID12]) AND ([Join12].[ID_Campo] = 50003041)
    UNION ALL
        SELECT 
        3 AS [C1], 
        [Limit3].[ID_Recorrencia] AS [ID_Recorrencia], 
        [Limit3].[ID_Usuario] AS [ID_Usuario], 
        [Limit3].[ID_Usuario1] AS [ID_Usuario1], 
        [Limit3].[ID] AS [ID], 
        [Limit3].[ID_Usuario2] AS [ID_Usuario2], 
        [Limit3].[ID1] AS [ID1], 
        [Limit3].[ID2] AS [ID2], 
        [Limit3].[ID_Usuario3] AS [ID_Usuario3], 
        [Limit3].[ID_Usuario4] AS [ID_Usuario4], 
        [Limit3].[ID3] AS [ID3], 
        [Limit3].[ID_Usuario] AS [ID_Usuario5], 
        [Limit3].[C1] AS [C2], 
        [Limit3].[ID_Usuario] AS [ID_Usuario6], 
        [Limit3].[C2] AS [C3], 
        [Limit3].[Descricao] AS [Descricao], 
        [Limit3].[ID_Usuario] AS [ID_Usuario7], 
        [Limit3].[C3] AS [C4], 
        [Limit3].[DataRecorrencia] AS [DataRecorrencia], 
        [Limit3].[ID_Usuario] AS [ID_Usuario8], 
        [Limit3].[C4] AS [C5], 
        [Limit3].[DataCriacao] AS [DataCriacao], 
        [Limit3].[ID_Usuario] AS [ID_Usuario9], 
        [Limit3].[C5] AS [C6], 
        [Limit3].[Concluido] AS [Concluido], 
        [Limit3].[ID_Usuario] AS [ID_Usuario10], 
        [Limit3].[C6] AS [C7], 
        [Limit3].[Longitude] AS [Longitude], 
        [Limit3].[ID_Usuario] AS [ID_Usuario11], 
        [Limit3].[C7] AS [C8], 
        [Limit3].[Latitude] AS [Latitude], 
        [Limit3].[ID_Usuario] AS [ID_Usuario12], 
        [Limit3].[C8] AS [C9], 
        [Limit3].[Titulo] AS [Titulo], 
        [Limit3].[ID_Usuario] AS [ID_Usuario13], 
        [Limit3].[C9] AS [C10], 
        [Limit3].[ID_Recorrencia] AS [ID_Recorrencia1], 
        [Limit3].[ID_Usuario] AS [ID_Usuario14], 
        [Limit3].[C10] AS [C11], 
        [Limit3].[ID_Usuario] AS [ID_Usuario15], 
        [Limit3].[C11] AS [C12], 
        [Limit3].[ID_Usuario] AS [ID_Usuario16], 
        [Limit3].[C12] AS [C13], 
        [Limit3].[Descricao1] AS [Descricao1], 
        [Limit3].[ID_Usuario] AS [ID_Usuario17], 
        [Limit3].[C13] AS [C14], 
        [Limit3].[ID_Classe] AS [ID_Classe], 
        [Limit3].[ID_Usuario] AS [ID_Usuario18], 
        [Limit3].[C14] AS [C15], 
        [Limit3].[ID_Usuario] AS [ID_Usuario19], 
        [Limit3].[C15] AS [C16], 
        [Limit3].[ID_Usuario] AS [ID_Usuario20], 
        [Limit3].[C16] AS [C17], 
        [Limit3].[ID_Usuario] AS [ID_Usuario21], 
        [Limit3].[C17] AS [C18], 
        [Limit3].[ID_Responsavel] AS [ID_Responsavel], 
        [Limit3].[ID_Usuario] AS [ID_Usuario22], 
        [Limit3].[C18] AS [C19], 
        [Limit3].[Nome] AS [Nome], 
        [Limit3].[ID_Usuario] AS [ID_Usuario23], 
        [Limit3].[C19] AS [C20], 
        [Limit3].[ID_Cliente] AS [ID_Cliente], 
        [Limit3].[ID_Usuario] AS [ID_Usuario24], 
        [Limit3].[C20] AS [C21], 
        [Limit3].[ID_Usuario] AS [ID_Usuario25], 
        [Limit3].[C21] AS [C22], 
        [Limit3].[ID_Usuario] AS [ID_Usuario26], 
        [Limit3].[C22] AS [C23], 
        [Limit3].[ID_Responsavel] AS [ID_Responsavel1], 
        [Limit3].[ID_Usuario] AS [ID_Usuario27], 
        [Limit3].[C23] AS [C24], 
        [Limit3].[C24] AS [C25], 
        [Limit3].[ID_Usuario] AS [ID_Usuario28], 
        [Limit3].[C25] AS [C26], 
        [Limit3].[ID_Usuario] AS [ID_Usuario29], 
        [Limit3].[C26] AS [C27], 
        [Limit3].[ID_Usuario] AS [ID_Usuario30], 
        [Limit3].[C27] AS [C28], 
        [Limit3].[Titulo1] AS [Titulo1], 
        [Limit3].[ID_Usuario] AS [ID_Usuario31], 
        [Limit3].[C28] AS [C29], 
        [Limit3].[ID_Oportunidade] AS [ID_Oportunidade], 
        [Limit3].[ID_Usuario] AS [ID_Usuario32], 
        [Limit3].[C29] AS [C30], 
        [Limit3].[ID_Usuario] AS [ID_Usuario33], 
        [Limit3].[C30] AS [C31], 
        [Limit3].[ID_Usuario] AS [ID_Usuario34], 
        [Limit3].[C31] AS [C32], 
        [Limit3].[AvatarUrl] AS [AvatarUrl], 
        [Limit3].[ID_Usuario] AS [ID_Usuario35], 
        [Limit3].[C32] AS [C33], 
        [Limit3].[Nome1] AS [Nome1], 
        [Limit3].[ID_Usuario] AS [ID_Usuario36], 
        [Limit3].[C33] AS [C34], 
        [Limit3].[ID_Responsavel1] AS [ID_Responsavel2], 
        [Limit3].[ID_Usuario] AS [ID_Usuario37], 
        [Limit3].[C34] AS [C35], 
        [Limit3].[C35] AS [C36], 
        [Limit3].[C36] AS [C37], 
        [Limit3].[C37] AS [C38], 
        [Limit3].[C38] AS [C39], 
        CAST(NULL AS int) AS [C40], 
        CAST(NULL AS varchar(1)) AS [C41], 
        CAST(NULL AS int) AS [C42], 
        CAST(NULL AS varchar(1)) AS [C43], 
        CAST(NULL AS int) AS [C44], 
        CAST(NULL AS int) AS [C45], 
        CAST(NULL AS varchar(1)) AS [C46], 
        CAST(NULL AS int) AS [C47], 
        CAST(NULL AS varchar(1)) AS [C48], 
        CAST(NULL AS int) AS [C49], 
        CAST(NULL AS varchar(1)) AS [C50], 
        CAST(NULL AS varchar(1)) AS [C51], 
        CAST(NULL AS int) AS [C52], 
        CAST(NULL AS varchar(1)) AS [C53], 
        CAST(NULL AS varchar(1)) AS [C54], 
        CAST(NULL AS int) AS [C55], 
        CAST(NULL AS varchar(1)) AS [C56], 
        CAST(NULL AS int) AS [C57], 
        CAST(NULL AS bit) AS [C58], 
        CAST(NULL AS int) AS [C59], 
        CAST(NULL AS varchar(1)) AS [C60], 
        CAST(NULL AS int) AS [C61], 
        CAST(NULL AS int) AS [C62], 
        CAST(NULL AS int) AS [C63], 
        CAST(NULL AS varchar(1)) AS [C64], 
        CAST(NULL AS int) AS [C65], 
        CAST(NULL AS varchar(1)) AS [C66], 
        CAST(NULL AS varchar(1)) AS [C67], 
        CAST(NULL AS int) AS [C68], 
        CAST(NULL AS float) AS [C69], 
        CAST(NULL AS datetime2) AS [C70], 
        CAST(NULL AS bit) AS [C71], 
        CAST(NULL AS int) AS [C72], 
        CAST(NULL AS varchar(1)) AS [C73], 
        CAST(NULL AS int) AS [C74], 
        CAST(NULL AS varchar(1)) AS [C75], 
        CAST(NULL AS varchar(1)) AS [C76], 
        CAST(NULL AS int) AS [C77], 
        CAST(NULL AS varchar(1)) AS [C78], 
        CAST(NULL AS int) AS [C79], 
        CAST(NULL AS varchar(1)) AS [C80], 
        CAST(NULL AS int) AS [C81], 
        CAST(NULL AS varchar(1)) AS [C82], 
        CAST(NULL AS int) AS [C83], 
        CAST(NULL AS varchar(1)) AS [C84], 
        CAST(NULL AS int) AS [C85], 
        CAST(NULL AS int) AS [C86], 
        CAST(NULL AS varchar(1)) AS [C87], 
        [Extent21].[ID_UsuarioView] AS [ID_UsuarioView], 
        N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C88], 
        [Extent21].[ID_UsuarioView] AS [ID_UsuarioView1], 
        [Extent21].[ID] AS [ID4], 
        [Extent21].[ID_Campo] AS [ID_Campo], 
        [Extent21].[Chave_Campo] AS [Chave_Campo], 
        [Extent21].[ID_Oportunidade] AS [ID_Oportunidade1], 
        [Extent21].[ValorTexto] AS [ValorTexto], 
        [Extent21].[ValorTextoMultilinha] AS [ValorTextoMultilinha], 
        [Extent21].[ValorInteiro] AS [ValorInteiro], 
        [Extent21].[ValorDecimal] AS [ValorDecimal], 
        [Extent21].[ValorDataHora] AS [ValorDataHora], 
        [Extent21].[ValorBooleano] AS [ValorBooleano], 
        [Extent21].[ID_OpcaoValor] AS [ID_OpcaoValor], 
        [Extent21].[ObjectValueName] AS [ObjectValueName], 
        [Extent21].[ID_UsuarioValor] AS [ID_UsuarioValor], 
        [Extent21].[UserValueName] AS [UserValueName], 
        [Extent21].[UserValueAvatarUrl] AS [UserValueAvatarUrl], 
        [Extent21].[ID_ProdutoValor] AS [ID_ProdutoValor], 
        [Extent21].[ProductValueName] AS [ProductValueName], 
        [Extent21].[AttachmentValueId] AS [AttachmentValueId], 
        [Extent21].[AttachmentValueName] AS [AttachmentValueName], 
        [Extent21].[ContactValueId] AS [ContactValueId], 
        [Extent21].[ContactValueName] AS [ContactValueName], 
        [Extent21].[ContactValueTypeId] AS [ContactValueTypeId], 
        [Extent21].[ContactValueRegister] AS [ContactValueRegister], 
        [Extent21].[CurrencyValueId] AS [CurrencyValueId], 
        [Extent21].[AttachmentItemValueId] AS [AttachmentItemValueId], 
        [Extent21].[AttachmentItemValueName] AS [AttachmentItemValueName]
        FROM   (SELECT TOP (75) [Project5].[ID_Usuario] AS [ID_Usuario], [Project5].[ID_Recorrencia] AS [ID_Recorrencia], [Project5].[Titulo] AS [Titulo], [Project5].[Descricao] AS [Descricao], [Project5].[ID_Classe] AS [ID_Classe], [Project5].[ID_Cliente] AS [ID_Cliente], [Project5].[ID_Oportunidade] AS [ID_Oportunidade], [Project5].[DataRecorrencia] AS [DataRecorrencia], [Project5].[Concluido] AS [Concluido], [Project5].[Latitude] AS [Latitude], [Project5].[Longitude] AS [Longitude], [Project5].[DataCriacao] AS [DataCriacao], [Project5].[ID_Usuario1] AS [ID_Usuario1], [Project5].[ID] AS [ID], [Project5].[Descricao1] AS [Descricao1], [Project5].[ID_Usuario2] AS [ID_Usuario2], [Project5].[ID1] AS [ID1], [Project5].[Nome] AS [Nome], [Project5].[ID_Responsavel] AS [ID_Responsavel], [Project5].[ID_Usuario3] AS [ID_Usuario3], [Project5].[ID2] AS [ID2], [Project5].[Titulo1] AS [Titulo1], [Project5].[ID_Responsavel1] AS [ID_Responsavel1], [Project5].[ID_Usuario4] AS [ID_Usuario4], [Project5].[ID3] AS [ID3], [Project5].[Nome1] AS [Nome1], [Project5].[AvatarUrl] AS [AvatarUrl], [Project5].[C1] AS [C1], [Project5].[C2] AS [C2], [Project5].[C3] AS [C3], [Project5].[C4] AS [C4], [Project5].[C5] AS [C5], [Project5].[C6] AS [C6], [Project5].[C7] AS [C7], [Project5].[C8] AS [C8], [Project5].[C9] AS [C9], [Project5].[C10] AS [C10], [Project5].[C11] AS [C11], [Project5].[C12] AS [C12], [Project5].[C13] AS [C13], [Project5].[C14] AS [C14], [Project5].[C15] AS [C15], [Project5].[C16] AS [C16], [Project5].[C17] AS [C17], [Project5].[C18] AS [C18], [Project5].[C19] AS [C19], [Project5].[C20] AS [C20], [Project5].[C21] AS [C21], [Project5].[C22] AS [C22], [Project5].[C23] AS [C23], [Project5].[C24] AS [C24], [Project5].[C25] AS [C25], [Project5].[C26] AS [C26], [Project5].[C27] AS [C27], [Project5].[C28] AS [C28], [Project5].[C29] AS [C29], [Project5].[C30] AS [C30], [Project5].[C31] AS [C31], [Project5].[C32] AS [C32], [Project5].[C33] AS [C33], [Project5].[C34] AS [C34], [Project5].[C35] AS [C35], [Project5].[C36] AS [C36], [Project5].[C37] AS [C37], [Project5].[C38] AS [C38]
            FROM ( SELECT 
                50003041 AS [p__linq__4], 
                10241922 AS [p__linq__5], 
                [Filter5].[ID_Usuario16] AS [ID_Usuario], 
                [Filter5].[ID_Recorrencia] AS [ID_Recorrencia], 
                [Filter5].[Titulo6] AS [Titulo], 
                [Filter5].[Descricao6] AS [Descricao], 
                [Filter5].[ID_Classe3] AS [ID_Classe], 
                [Filter5].[ID_Cliente3] AS [ID_Cliente], 
                [Filter5].[ID_Oportunidade] AS [ID_Oportunidade], 
                [Filter5].[DataRecorrencia] AS [DataRecorrencia], 
                [Filter5].[Concluido] AS [Concluido], 
                [Filter5].[Latitude] AS [Latitude], 
                [Filter5].[Longitude] AS [Longitude], 
                [Filter5].[DataCriacao3] AS [DataCriacao], 
                [Filter5].[ID_Usuario17] AS [ID_Usuario1], 
                [Filter5].[ID13] AS [ID], 
                [Filter5].[Descricao7] AS [Descricao1], 
                [Filter5].[ID_Usuario18] AS [ID_Usuario2], 
                [Filter5].[ID14] AS [ID1], 
                [Filter5].[Nome] AS [Nome], 
                [Filter5].[ID_Responsavel6] AS [ID_Responsavel], 
                [Filter5].[ID_Usuario19] AS [ID_Usuario3], 
                [Filter5].[ID15] AS [ID2], 
                [Filter5].[Titulo7] AS [Titulo1], 
                [Filter5].[ID_Responsavel7] AS [ID_Responsavel1], 
                [Extent20].[ID_Usuario] AS [ID_Usuario4], 
                [Extent20].[ID] AS [ID3], 
                [Extent20].[Nome] AS [Nome1], 
                [Extent20].[AvatarUrl] AS [AvatarUrl], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C1], 
                N'Description' AS [C2], 
                N'DateTime' AS [C3], 
                N'CreateDate' AS [C4], 
                N'Finished' AS [C5], 
                N'Longitude' AS [C6], 
                N'Latitude' AS [C7], 
                N'Title' AS [C8], 
                N'Id' AS [C9], 
                N'Type' AS [C10], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C11], 
                N'Name' AS [C12], 
                N'Id' AS [C13], 
                N'Users' AS [C14], 
                N'Contact' AS [C15], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C16], 
                N'OwnerId' AS [C17], 
                N'Name' AS [C18], 
                N'Id' AS [C19], 
                N'Owner' AS [C20], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C21], 
                N'Id' AS [C22], 
                N'OtherProperties' AS [C23], 
                CASE WHEN ([Filter5].[ID_Responsavel6] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C24], 
                N'Deal' AS [C25], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C26], 
                N'Title' AS [C27], 
                N'Id' AS [C28], 
                N'Owner' AS [C29], 
                N'88b58adb-a9d5-4511-98a9-8090cf7ea9dc' AS [C30], 
                N'AvatarUrl' AS [C31], 
                N'Name' AS [C32], 
                N'Id' AS [C33], 
                N'OtherProperties' AS [C34], 
                CASE WHEN ([Filter5].[ID_Responsavel7] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C35], 
                CASE WHEN ([Filter5].[ID_Oportunidade] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C36], 
                CASE WHEN ([Filter5].[ID_Cliente3] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C37], 
                CASE WHEN ([Filter5].[ID_Classe3] IS NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C38]
                FROM   (SELECT [Extent16].[ID_Usuario] AS [ID_Usuario16], [Extent16].[ID_Recorrencia] AS [ID_Recorrencia], [Extent16].[Titulo] AS [Titulo6], [Extent16].[Descricao] AS [Descricao6], [Extent16].[ID_Classe] AS [ID_Classe3], [Extent16].[ID_Cliente] AS [ID_Cliente3], [Extent16].[ID_Oportunidade] AS [ID_Oportunidade], [Extent16].[DataRecorrencia] AS [DataRecorrencia], [Extent16].[Concluido] AS [Concluido], [Extent16].[Latitude] AS [Latitude], [Extent16].[Longitude] AS [Longitude], [Extent16].[DataCriacao] AS [DataCriacao3], [Extent17].[ID_Usuario] AS [ID_Usuario17], [Extent17].[ID] AS [ID13], [Extent17].[Descricao] AS [Descricao7], [Extent18].[ID_Usuario] AS [ID_Usuario18], [Extent18].[ID] AS [ID14], [Extent18].[Nome] AS [Nome], [Extent18].[ID_Responsavel] AS [ID_Responsavel6], [Extent19].[ID_Usuario] AS [ID_Usuario19], [Extent19].[ID] AS [ID15], [Extent19].[Titulo] AS [Titulo7], [Extent19].[ID_Responsavel] AS [ID_Responsavel7]
                    FROM    [dbo].[SVw_Tarefa] AS [Extent16]
                    LEFT OUTER JOIN [dbo].[SVw_Tarefa_Classe] AS [Extent17] ON ([Extent16].[ID_Usuario] = [Extent17].[ID_Usuario]) AND ([Extent16].[ID_Classe] = [Extent17].[ID])
                    LEFT OUTER JOIN [dbo].[SVw_Cliente] AS [Extent18] ON ([Extent16].[ID_Usuario] = [Extent18].[ID_Usuario]) AND ([Extent16].[ID_Cliente] = [Extent18].[ID])
                    LEFT OUTER JOIN [dbo].[SVw_Oportunidade] AS [Extent19] ON ([Extent16].[ID_Usuario] = [Extent19].[ID_Usuario]) AND ([Extent16].[ID_Oportunidade] = [Extent19].[ID])
                    WHERE [Extent16].[ID_Recorrencia] > 0 ) AS [Filter5]
                LEFT OUTER JOIN [dbo].[SVw_Usuario] AS [Extent20] ON ([Filter5].[ID_Usuario19] = [Extent20].[ID_Usuario]) AND ([Filter5].[ID_Responsavel7] = [Extent20].[ID])
                WHERE ([Filter5].[ID_Usuario16] = 10031617) AND ([Filter5].[Concluido] = 0) AND ([Filter5].[ID_Recorrencia] > 500349367)
            )  AS [Project5]
            ORDER BY [Project5].[ID_Recorrencia] ASC ) AS [Limit3]
        INNER JOIN [dbo].[SVw_Campo_Valor_Oportunidade] AS [Extent21] ON ([Limit3].[ID_Oportunidade] = [Extent21].[ID_Oportunidade]) AND ([Limit3].[ID_Usuario] = [Extent21].[ID_UsuarioView]) AND ([Extent21].[ID_Campo] = 10241922)
        WHERE [Extent21].[ID_Oportunidade] IS NOT NULL) AS [UnionAll2]
    ORDER BY [UnionAll2].[ID_Recorrencia] ASC, [UnionAll2].[ID_Usuario] ASC, [UnionAll2].[ID_Usuario1] ASC, [UnionAll2].[ID] ASC, [UnionAll2].[ID_Usuario2] ASC, [UnionAll2].[ID1] ASC, [UnionAll2].[ID2] ASC, [UnionAll2].[ID_Usuario3] ASC, [UnionAll2].[ID_Usuario4] ASC, [UnionAll2].[ID3] ASC, [UnionAll2].[C1] ASC