USE [master]
GO

--drop database [Integrations]
CREATE DATABASE [Integrations]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Integrations', FILENAME = N'F:\DATA\Integrations.mdf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB)
 LOG ON 
( NAME = N'Integrations_log', FILENAME = N'F:\DATA\Integrations_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 100MB)
 COLLATE SQL_Latin1_General_CP1_CI_AS
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

--drop database [logs]
CREATE DATABASE [logs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Logs', FILENAME = N'F:\DATA\logs.mdf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB )
 LOG ON 
( NAME = N'Logs_log', FILENAME = N'F:\DATA\logs_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 100MB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

--drop database [Queue]
CREATE DATABASE [Queue]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Queue', FILENAME = N'F:\DATA\Queue.mdf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB )
 LOG ON 
( NAME = N'Queue_log', FILENAME = N'F:\DATA\Queue_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 100MB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

--drop database Temp
CREATE DATABASE [Temp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Temp', FILENAME = N'D:\SQL\DATA\Temp.mdf' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB )
 LOG ON 
( NAME = N'Temp_log', FILENAME = N'D:\SQL\DATA\Temp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 100MB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO